/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: battery.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "battery.pb-c.h"
void   insta360__messages__battery_status__init
                     (Insta360__Messages__BatteryStatus         *message)
{
  static const Insta360__Messages__BatteryStatus init_value = INSTA360__MESSAGES__BATTERY_STATUS__INIT;
  *message = init_value;
}
size_t insta360__messages__battery_status__get_packed_size
                     (const Insta360__Messages__BatteryStatus *message)
{
  assert(message->base.descriptor == &insta360__messages__battery_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__battery_status__pack
                     (const Insta360__Messages__BatteryStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__battery_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__battery_status__pack_to_buffer
                     (const Insta360__Messages__BatteryStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__battery_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__BatteryStatus *
       insta360__messages__battery_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__BatteryStatus *)
     protobuf_c_message_unpack (&insta360__messages__battery_status__descriptor,
                                allocator, len, data);
}
void   insta360__messages__battery_status__free_unpacked
                     (Insta360__Messages__BatteryStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__battery_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue insta360__messages__battery_status__power_type__enum_values_by_number[2] =
{
  { "BATTERY", "INSTA360__MESSAGES__BATTERY_STATUS__POWER_TYPE__BATTERY", 0 },
  { "ADAPTER", "INSTA360__MESSAGES__BATTERY_STATUS__POWER_TYPE__ADAPTER", 1 },
};
static const ProtobufCIntRange insta360__messages__battery_status__power_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex insta360__messages__battery_status__power_type__enum_values_by_name[2] =
{
  { "ADAPTER", 1 },
  { "BATTERY", 0 },
};
const ProtobufCEnumDescriptor insta360__messages__battery_status__power_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.BatteryStatus.PowerType",
  "PowerType",
  "Insta360__Messages__BatteryStatus__PowerType",
  "insta360.messages",
  2,
  insta360__messages__battery_status__power_type__enum_values_by_number,
  2,
  insta360__messages__battery_status__power_type__enum_values_by_name,
  1,
  insta360__messages__battery_status__power_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor insta360__messages__battery_status__field_descriptors[3] =
{
  {
    "power_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__BatteryStatus, power_type),
    &insta360__messages__battery_status__power_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_level",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__BatteryStatus, battery_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_scale",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__BatteryStatus, battery_scale),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__battery_status__field_indices_by_name[] = {
  1,   /* field[1] = battery_level */
  2,   /* field[2] = battery_scale */
  0,   /* field[0] = power_type */
};
static const ProtobufCIntRange insta360__messages__battery_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor insta360__messages__battery_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.BatteryStatus",
  "BatteryStatus",
  "Insta360__Messages__BatteryStatus",
  "insta360.messages",
  sizeof(Insta360__Messages__BatteryStatus),
  3,
  insta360__messages__battery_status__field_descriptors,
  insta360__messages__battery_status__field_indices_by_name,
  1,  insta360__messages__battery_status__number_ranges,
  (ProtobufCMessageInit) insta360__messages__battery_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
