/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: battery_low.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "battery_low.pb-c.h"
void   insta360__messages__notification_battery_low__init
                     (Insta360__Messages__NotificationBatteryLow         *message)
{
  static const Insta360__Messages__NotificationBatteryLow init_value = INSTA360__MESSAGES__NOTIFICATION_BATTERY_LOW__INIT;
  *message = init_value;
}
size_t insta360__messages__notification_battery_low__get_packed_size
                     (const Insta360__Messages__NotificationBatteryLow *message)
{
  assert(message->base.descriptor == &insta360__messages__notification_battery_low__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__notification_battery_low__pack
                     (const Insta360__Messages__NotificationBatteryLow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__notification_battery_low__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__notification_battery_low__pack_to_buffer
                     (const Insta360__Messages__NotificationBatteryLow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__notification_battery_low__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__NotificationBatteryLow *
       insta360__messages__notification_battery_low__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__NotificationBatteryLow *)
     protobuf_c_message_unpack (&insta360__messages__notification_battery_low__descriptor,
                                allocator, len, data);
}
void   insta360__messages__notification_battery_low__free_unpacked
                     (Insta360__Messages__NotificationBatteryLow *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__notification_battery_low__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__notification_battery_low__field_descriptors[1] =
{
  {
    "battery_status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__NotificationBatteryLow, battery_status),
    &insta360__messages__battery_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__notification_battery_low__field_indices_by_name[] = {
  0,   /* field[0] = battery_status */
};
static const ProtobufCIntRange insta360__messages__notification_battery_low__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__notification_battery_low__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.NotificationBatteryLow",
  "NotificationBatteryLow",
  "Insta360__Messages__NotificationBatteryLow",
  "insta360.messages",
  sizeof(Insta360__Messages__NotificationBatteryLow),
  1,
  insta360__messages__notification_battery_low__field_descriptors,
  insta360__messages__notification_battery_low__field_indices_by_name,
  1,  insta360__messages__notification_battery_low__number_ranges,
  (ProtobufCMessageInit) insta360__messages__notification_battery_low__init,
  NULL,NULL,NULL    /* reserved[123] */
};
