/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: battery.proto */

#ifndef PROTOBUF_C_battery_2eproto__INCLUDED
#define PROTOBUF_C_battery_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__BatteryStatus Insta360__Messages__BatteryStatus;


/* --- enums --- */

typedef enum _Insta360__Messages__BatteryStatus__PowerType {
  INSTA360__MESSAGES__BATTERY_STATUS__POWER_TYPE__BATTERY = 0,
  INSTA360__MESSAGES__BATTERY_STATUS__POWER_TYPE__ADAPTER = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__BATTERY_STATUS__POWER_TYPE)
} Insta360__Messages__BatteryStatus__PowerType;

/* --- messages --- */

struct  Insta360__Messages__BatteryStatus
{
  ProtobufCMessage base;
  Insta360__Messages__BatteryStatus__PowerType power_type;
  uint32_t battery_level;
  uint32_t battery_scale;
};
#define INSTA360__MESSAGES__BATTERY_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__battery_status__descriptor) \
    , INSTA360__MESSAGES__BATTERY_STATUS__POWER_TYPE__BATTERY, 0, 0 }


/* Insta360__Messages__BatteryStatus methods */
void   insta360__messages__battery_status__init
                     (Insta360__Messages__BatteryStatus         *message);
size_t insta360__messages__battery_status__get_packed_size
                     (const Insta360__Messages__BatteryStatus   *message);
size_t insta360__messages__battery_status__pack
                     (const Insta360__Messages__BatteryStatus   *message,
                      uint8_t             *out);
size_t insta360__messages__battery_status__pack_to_buffer
                     (const Insta360__Messages__BatteryStatus   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__BatteryStatus *
       insta360__messages__battery_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__battery_status__free_unpacked
                     (Insta360__Messages__BatteryStatus *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__BatteryStatus_Closure)
                 (const Insta360__Messages__BatteryStatus *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__battery_status__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__battery_status__power_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_battery_2eproto__INCLUDED */
