/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bluetooth.proto */

#ifndef PROTOBUF_C_bluetooth_2eproto__INCLUDED
#define PROTOBUF_C_bluetooth_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__BTPeripheral Insta360__Messages__BTPeripheral;


/* --- enums --- */

typedef enum _Insta360__Messages__BTPeripheralType {
  INSTA360__MESSAGES__BTPERIPHERAL_TYPE__ALL = 0,
  INSTA360__MESSAGES__BTPERIPHERAL_TYPE__REMOTE_CONTROLLER = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__BTPERIPHERAL_TYPE)
} Insta360__Messages__BTPeripheralType;

/* --- messages --- */

struct  Insta360__Messages__BTPeripheral
{
  ProtobufCMessage base;
  char *name;
  ProtobufCBinaryData mac_addr;
};
#define INSTA360__MESSAGES__BTPERIPHERAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__btperipheral__descriptor) \
    , (char *)protobuf_c_empty_string, {0,NULL} }


/* Insta360__Messages__BTPeripheral methods */
void   insta360__messages__btperipheral__init
                     (Insta360__Messages__BTPeripheral         *message);
size_t insta360__messages__btperipheral__get_packed_size
                     (const Insta360__Messages__BTPeripheral   *message);
size_t insta360__messages__btperipheral__pack
                     (const Insta360__Messages__BTPeripheral   *message,
                      uint8_t             *out);
size_t insta360__messages__btperipheral__pack_to_buffer
                     (const Insta360__Messages__BTPeripheral   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__BTPeripheral *
       insta360__messages__btperipheral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__btperipheral__free_unpacked
                     (Insta360__Messages__BTPeripheral *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__BTPeripheral_Closure)
                 (const Insta360__Messages__BTPeripheral *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    insta360__messages__btperipheral_type__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__btperipheral__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_bluetooth_2eproto__INCLUDED */
