/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bluetooth.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "bluetooth.pb-c.h"
void   insta360__messages__btperipheral__init
                     (Insta360__Messages__BTPeripheral         *message)
{
  static const Insta360__Messages__BTPeripheral init_value = INSTA360__MESSAGES__BTPERIPHERAL__INIT;
  *message = init_value;
}
size_t insta360__messages__btperipheral__get_packed_size
                     (const Insta360__Messages__BTPeripheral *message)
{
  assert(message->base.descriptor == &insta360__messages__btperipheral__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__btperipheral__pack
                     (const Insta360__Messages__BTPeripheral *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__btperipheral__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__btperipheral__pack_to_buffer
                     (const Insta360__Messages__BTPeripheral *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__btperipheral__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__BTPeripheral *
       insta360__messages__btperipheral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__BTPeripheral *)
     protobuf_c_message_unpack (&insta360__messages__btperipheral__descriptor,
                                allocator, len, data);
}
void   insta360__messages__btperipheral__free_unpacked
                     (Insta360__Messages__BTPeripheral *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__btperipheral__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__btperipheral__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__BTPeripheral, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__BTPeripheral, mac_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__btperipheral__field_indices_by_name[] = {
  1,   /* field[1] = mac_addr */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange insta360__messages__btperipheral__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__btperipheral__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.BTPeripheral",
  "BTPeripheral",
  "Insta360__Messages__BTPeripheral",
  "insta360.messages",
  sizeof(Insta360__Messages__BTPeripheral),
  2,
  insta360__messages__btperipheral__field_descriptors,
  insta360__messages__btperipheral__field_indices_by_name,
  1,  insta360__messages__btperipheral__number_ranges,
  (ProtobufCMessageInit) insta360__messages__btperipheral__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue insta360__messages__btperipheral_type__enum_values_by_number[2] =
{
  { "ALL", "INSTA360__MESSAGES__BTPERIPHERAL_TYPE__ALL", 0 },
  { "REMOTE_CONTROLLER", "INSTA360__MESSAGES__BTPERIPHERAL_TYPE__REMOTE_CONTROLLER", 1 },
};
static const ProtobufCIntRange insta360__messages__btperipheral_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex insta360__messages__btperipheral_type__enum_values_by_name[2] =
{
  { "ALL", 0 },
  { "REMOTE_CONTROLLER", 1 },
};
const ProtobufCEnumDescriptor insta360__messages__btperipheral_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.BTPeripheralType",
  "BTPeripheralType",
  "Insta360__Messages__BTPeripheralType",
  "insta360.messages",
  2,
  insta360__messages__btperipheral_type__enum_values_by_number,
  2,
  insta360__messages__btperipheral_type__enum_values_by_name,
  1,
  insta360__messages__btperipheral_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
