/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bt_central.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "bt_central.pb-c.h"
void   insta360__messages__scan_btperipheral__init
                     (Insta360__Messages__ScanBTPeripheral         *message)
{
  static const Insta360__Messages__ScanBTPeripheral init_value = INSTA360__MESSAGES__SCAN_BTPERIPHERAL__INIT;
  *message = init_value;
}
size_t insta360__messages__scan_btperipheral__get_packed_size
                     (const Insta360__Messages__ScanBTPeripheral *message)
{
  assert(message->base.descriptor == &insta360__messages__scan_btperipheral__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__scan_btperipheral__pack
                     (const Insta360__Messages__ScanBTPeripheral *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__scan_btperipheral__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__scan_btperipheral__pack_to_buffer
                     (const Insta360__Messages__ScanBTPeripheral *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__scan_btperipheral__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__ScanBTPeripheral *
       insta360__messages__scan_btperipheral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__ScanBTPeripheral *)
     protobuf_c_message_unpack (&insta360__messages__scan_btperipheral__descriptor,
                                allocator, len, data);
}
void   insta360__messages__scan_btperipheral__free_unpacked
                     (Insta360__Messages__ScanBTPeripheral *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__scan_btperipheral__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__connect_to_btperipheral__init
                     (Insta360__Messages__ConnectToBTPeripheral         *message)
{
  static const Insta360__Messages__ConnectToBTPeripheral init_value = INSTA360__MESSAGES__CONNECT_TO_BTPERIPHERAL__INIT;
  *message = init_value;
}
size_t insta360__messages__connect_to_btperipheral__get_packed_size
                     (const Insta360__Messages__ConnectToBTPeripheral *message)
{
  assert(message->base.descriptor == &insta360__messages__connect_to_btperipheral__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__connect_to_btperipheral__pack
                     (const Insta360__Messages__ConnectToBTPeripheral *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__connect_to_btperipheral__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__connect_to_btperipheral__pack_to_buffer
                     (const Insta360__Messages__ConnectToBTPeripheral *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__connect_to_btperipheral__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__ConnectToBTPeripheral *
       insta360__messages__connect_to_btperipheral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__ConnectToBTPeripheral *)
     protobuf_c_message_unpack (&insta360__messages__connect_to_btperipheral__descriptor,
                                allocator, len, data);
}
void   insta360__messages__connect_to_btperipheral__free_unpacked
                     (Insta360__Messages__ConnectToBTPeripheral *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__connect_to_btperipheral__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__disconnect_btperipheral__init
                     (Insta360__Messages__DisconnectBTPeripheral         *message)
{
  static const Insta360__Messages__DisconnectBTPeripheral init_value = INSTA360__MESSAGES__DISCONNECT_BTPERIPHERAL__INIT;
  *message = init_value;
}
size_t insta360__messages__disconnect_btperipheral__get_packed_size
                     (const Insta360__Messages__DisconnectBTPeripheral *message)
{
  assert(message->base.descriptor == &insta360__messages__disconnect_btperipheral__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__disconnect_btperipheral__pack
                     (const Insta360__Messages__DisconnectBTPeripheral *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__disconnect_btperipheral__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__disconnect_btperipheral__pack_to_buffer
                     (const Insta360__Messages__DisconnectBTPeripheral *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__disconnect_btperipheral__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__DisconnectBTPeripheral *
       insta360__messages__disconnect_btperipheral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__DisconnectBTPeripheral *)
     protobuf_c_message_unpack (&insta360__messages__disconnect_btperipheral__descriptor,
                                allocator, len, data);
}
void   insta360__messages__disconnect_btperipheral__free_unpacked
                     (Insta360__Messages__DisconnectBTPeripheral *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__disconnect_btperipheral__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__get_connected_btperipheral__init
                     (Insta360__Messages__GetConnectedBTPeripheral         *message)
{
  static const Insta360__Messages__GetConnectedBTPeripheral init_value = INSTA360__MESSAGES__GET_CONNECTED_BTPERIPHERAL__INIT;
  *message = init_value;
}
size_t insta360__messages__get_connected_btperipheral__get_packed_size
                     (const Insta360__Messages__GetConnectedBTPeripheral *message)
{
  assert(message->base.descriptor == &insta360__messages__get_connected_btperipheral__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__get_connected_btperipheral__pack
                     (const Insta360__Messages__GetConnectedBTPeripheral *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__get_connected_btperipheral__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__get_connected_btperipheral__pack_to_buffer
                     (const Insta360__Messages__GetConnectedBTPeripheral *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__get_connected_btperipheral__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__GetConnectedBTPeripheral *
       insta360__messages__get_connected_btperipheral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__GetConnectedBTPeripheral *)
     protobuf_c_message_unpack (&insta360__messages__get_connected_btperipheral__descriptor,
                                allocator, len, data);
}
void   insta360__messages__get_connected_btperipheral__free_unpacked
                     (Insta360__Messages__GetConnectedBTPeripheral *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__get_connected_btperipheral__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__get_connected_btperipheral_resp__init
                     (Insta360__Messages__GetConnectedBTPeripheralResp         *message)
{
  static const Insta360__Messages__GetConnectedBTPeripheralResp init_value = INSTA360__MESSAGES__GET_CONNECTED_BTPERIPHERAL_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__get_connected_btperipheral_resp__get_packed_size
                     (const Insta360__Messages__GetConnectedBTPeripheralResp *message)
{
  assert(message->base.descriptor == &insta360__messages__get_connected_btperipheral_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__get_connected_btperipheral_resp__pack
                     (const Insta360__Messages__GetConnectedBTPeripheralResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__get_connected_btperipheral_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__get_connected_btperipheral_resp__pack_to_buffer
                     (const Insta360__Messages__GetConnectedBTPeripheralResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__get_connected_btperipheral_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__GetConnectedBTPeripheralResp *
       insta360__messages__get_connected_btperipheral_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__GetConnectedBTPeripheralResp *)
     protobuf_c_message_unpack (&insta360__messages__get_connected_btperipheral_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__get_connected_btperipheral_resp__free_unpacked
                     (Insta360__Messages__GetConnectedBTPeripheralResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__get_connected_btperipheral_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__scan_btperipheral__field_descriptors[1] =
{
  {
    "peripheral_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__ScanBTPeripheral, peripheral_type),
    &insta360__messages__btperipheral_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__scan_btperipheral__field_indices_by_name[] = {
  0,   /* field[0] = peripheral_type */
};
static const ProtobufCIntRange insta360__messages__scan_btperipheral__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__scan_btperipheral__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.ScanBTPeripheral",
  "ScanBTPeripheral",
  "Insta360__Messages__ScanBTPeripheral",
  "insta360.messages",
  sizeof(Insta360__Messages__ScanBTPeripheral),
  1,
  insta360__messages__scan_btperipheral__field_descriptors,
  insta360__messages__scan_btperipheral__field_indices_by_name,
  1,  insta360__messages__scan_btperipheral__number_ranges,
  (ProtobufCMessageInit) insta360__messages__scan_btperipheral__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__connect_to_btperipheral__field_descriptors[1] =
{
  {
    "peripheral",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__ConnectToBTPeripheral, peripheral),
    &insta360__messages__btperipheral__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__connect_to_btperipheral__field_indices_by_name[] = {
  0,   /* field[0] = peripheral */
};
static const ProtobufCIntRange insta360__messages__connect_to_btperipheral__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__connect_to_btperipheral__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.ConnectToBTPeripheral",
  "ConnectToBTPeripheral",
  "Insta360__Messages__ConnectToBTPeripheral",
  "insta360.messages",
  sizeof(Insta360__Messages__ConnectToBTPeripheral),
  1,
  insta360__messages__connect_to_btperipheral__field_descriptors,
  insta360__messages__connect_to_btperipheral__field_indices_by_name,
  1,  insta360__messages__connect_to_btperipheral__number_ranges,
  (ProtobufCMessageInit) insta360__messages__connect_to_btperipheral__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__disconnect_btperipheral__field_descriptors[1] =
{
  {
    "peripheral",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__DisconnectBTPeripheral, peripheral),
    &insta360__messages__btperipheral__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__disconnect_btperipheral__field_indices_by_name[] = {
  0,   /* field[0] = peripheral */
};
static const ProtobufCIntRange insta360__messages__disconnect_btperipheral__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__disconnect_btperipheral__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.DisconnectBTPeripheral",
  "DisconnectBTPeripheral",
  "Insta360__Messages__DisconnectBTPeripheral",
  "insta360.messages",
  sizeof(Insta360__Messages__DisconnectBTPeripheral),
  1,
  insta360__messages__disconnect_btperipheral__field_descriptors,
  insta360__messages__disconnect_btperipheral__field_indices_by_name,
  1,  insta360__messages__disconnect_btperipheral__number_ranges,
  (ProtobufCMessageInit) insta360__messages__disconnect_btperipheral__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__get_connected_btperipheral__field_descriptors[1] =
{
  {
    "peripheral_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetConnectedBTPeripheral, peripheral_type),
    &insta360__messages__btperipheral_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_connected_btperipheral__field_indices_by_name[] = {
  0,   /* field[0] = peripheral_type */
};
static const ProtobufCIntRange insta360__messages__get_connected_btperipheral__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__get_connected_btperipheral__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetConnectedBTPeripheral",
  "GetConnectedBTPeripheral",
  "Insta360__Messages__GetConnectedBTPeripheral",
  "insta360.messages",
  sizeof(Insta360__Messages__GetConnectedBTPeripheral),
  1,
  insta360__messages__get_connected_btperipheral__field_descriptors,
  insta360__messages__get_connected_btperipheral__field_indices_by_name,
  1,  insta360__messages__get_connected_btperipheral__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_connected_btperipheral__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__get_connected_btperipheral_resp__field_descriptors[1] =
{
  {
    "peripherals",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Insta360__Messages__GetConnectedBTPeripheralResp, n_peripherals),
    offsetof(Insta360__Messages__GetConnectedBTPeripheralResp, peripherals),
    &insta360__messages__btperipheral__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_connected_btperipheral_resp__field_indices_by_name[] = {
  0,   /* field[0] = peripherals */
};
static const ProtobufCIntRange insta360__messages__get_connected_btperipheral_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__get_connected_btperipheral_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetConnectedBTPeripheralResp",
  "GetConnectedBTPeripheralResp",
  "Insta360__Messages__GetConnectedBTPeripheralResp",
  "insta360.messages",
  sizeof(Insta360__Messages__GetConnectedBTPeripheralResp),
  1,
  insta360__messages__get_connected_btperipheral_resp__field_descriptors,
  insta360__messages__get_connected_btperipheral_resp__field_indices_by_name,
  1,  insta360__messages__get_connected_btperipheral_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_connected_btperipheral_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
