/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bt_central_notification.proto */

#ifndef PROTOBUF_C_bt_5fcentral_5fnotification_2eproto__INCLUDED
#define PROTOBUF_C_bt_5fcentral_5fnotification_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "bluetooth.pb-c.h"

typedef struct Insta360__Messages__NotificatoinDiscoverBTPeripheral Insta360__Messages__NotificatoinDiscoverBTPeripheral;
typedef struct Insta360__Messages__NotificatoinConnectedToPeripheral Insta360__Messages__NotificatoinConnectedToPeripheral;
typedef struct Insta360__Messages__NotificatoinDisconnectedPeripheral Insta360__Messages__NotificatoinDisconnectedPeripheral;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__NotificatoinDiscoverBTPeripheral
{
  ProtobufCMessage base;
  size_t n_peripherals;
  Insta360__Messages__BTPeripheral **peripherals;
};
#define INSTA360__MESSAGES__NOTIFICATOIN_DISCOVER_BTPERIPHERAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__notificatoin_discover_btperipheral__descriptor) \
    , 0,NULL }


struct  Insta360__Messages__NotificatoinConnectedToPeripheral
{
  ProtobufCMessage base;
  Insta360__Messages__BTPeripheral *peripheral;
};
#define INSTA360__MESSAGES__NOTIFICATOIN_CONNECTED_TO_PERIPHERAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__notificatoin_connected_to_peripheral__descriptor) \
    , NULL }


struct  Insta360__Messages__NotificatoinDisconnectedPeripheral
{
  ProtobufCMessage base;
  Insta360__Messages__BTPeripheral *peripheral;
};
#define INSTA360__MESSAGES__NOTIFICATOIN_DISCONNECTED_PERIPHERAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__notificatoin_disconnected_peripheral__descriptor) \
    , NULL }


/* Insta360__Messages__NotificatoinDiscoverBTPeripheral methods */
void   insta360__messages__notificatoin_discover_btperipheral__init
                     (Insta360__Messages__NotificatoinDiscoverBTPeripheral         *message);
size_t insta360__messages__notificatoin_discover_btperipheral__get_packed_size
                     (const Insta360__Messages__NotificatoinDiscoverBTPeripheral   *message);
size_t insta360__messages__notificatoin_discover_btperipheral__pack
                     (const Insta360__Messages__NotificatoinDiscoverBTPeripheral   *message,
                      uint8_t             *out);
size_t insta360__messages__notificatoin_discover_btperipheral__pack_to_buffer
                     (const Insta360__Messages__NotificatoinDiscoverBTPeripheral   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__NotificatoinDiscoverBTPeripheral *
       insta360__messages__notificatoin_discover_btperipheral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__notificatoin_discover_btperipheral__free_unpacked
                     (Insta360__Messages__NotificatoinDiscoverBTPeripheral *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__NotificatoinConnectedToPeripheral methods */
void   insta360__messages__notificatoin_connected_to_peripheral__init
                     (Insta360__Messages__NotificatoinConnectedToPeripheral         *message);
size_t insta360__messages__notificatoin_connected_to_peripheral__get_packed_size
                     (const Insta360__Messages__NotificatoinConnectedToPeripheral   *message);
size_t insta360__messages__notificatoin_connected_to_peripheral__pack
                     (const Insta360__Messages__NotificatoinConnectedToPeripheral   *message,
                      uint8_t             *out);
size_t insta360__messages__notificatoin_connected_to_peripheral__pack_to_buffer
                     (const Insta360__Messages__NotificatoinConnectedToPeripheral   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__NotificatoinConnectedToPeripheral *
       insta360__messages__notificatoin_connected_to_peripheral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__notificatoin_connected_to_peripheral__free_unpacked
                     (Insta360__Messages__NotificatoinConnectedToPeripheral *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__NotificatoinDisconnectedPeripheral methods */
void   insta360__messages__notificatoin_disconnected_peripheral__init
                     (Insta360__Messages__NotificatoinDisconnectedPeripheral         *message);
size_t insta360__messages__notificatoin_disconnected_peripheral__get_packed_size
                     (const Insta360__Messages__NotificatoinDisconnectedPeripheral   *message);
size_t insta360__messages__notificatoin_disconnected_peripheral__pack
                     (const Insta360__Messages__NotificatoinDisconnectedPeripheral   *message,
                      uint8_t             *out);
size_t insta360__messages__notificatoin_disconnected_peripheral__pack_to_buffer
                     (const Insta360__Messages__NotificatoinDisconnectedPeripheral   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__NotificatoinDisconnectedPeripheral *
       insta360__messages__notificatoin_disconnected_peripheral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__notificatoin_disconnected_peripheral__free_unpacked
                     (Insta360__Messages__NotificatoinDisconnectedPeripheral *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__NotificatoinDiscoverBTPeripheral_Closure)
                 (const Insta360__Messages__NotificatoinDiscoverBTPeripheral *message,
                  void *closure_data);
typedef void (*Insta360__Messages__NotificatoinConnectedToPeripheral_Closure)
                 (const Insta360__Messages__NotificatoinConnectedToPeripheral *message,
                  void *closure_data);
typedef void (*Insta360__Messages__NotificatoinDisconnectedPeripheral_Closure)
                 (const Insta360__Messages__NotificatoinDisconnectedPeripheral *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__notificatoin_discover_btperipheral__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__notificatoin_connected_to_peripheral__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__notificatoin_disconnected_peripheral__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_bt_5fcentral_5fnotification_2eproto__INCLUDED */
