/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: calibrate_gyro.proto */

#ifndef PROTOBUF_C_calibrate_5fgyro_2eproto__INCLUDED
#define PROTOBUF_C_calibrate_5fgyro_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__CalibrateGyro Insta360__Messages__CalibrateGyro;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__CalibrateGyro
{
  ProtobufCMessage base;
  uint32_t gyro_count;
};
#define INSTA360__MESSAGES__CALIBRATE_GYRO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__calibrate_gyro__descriptor) \
    , 0 }


/* Insta360__Messages__CalibrateGyro methods */
void   insta360__messages__calibrate_gyro__init
                     (Insta360__Messages__CalibrateGyro         *message);
size_t insta360__messages__calibrate_gyro__get_packed_size
                     (const Insta360__Messages__CalibrateGyro   *message);
size_t insta360__messages__calibrate_gyro__pack
                     (const Insta360__Messages__CalibrateGyro   *message,
                      uint8_t             *out);
size_t insta360__messages__calibrate_gyro__pack_to_buffer
                     (const Insta360__Messages__CalibrateGyro   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__CalibrateGyro *
       insta360__messages__calibrate_gyro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__calibrate_gyro__free_unpacked
                     (Insta360__Messages__CalibrateGyro *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__CalibrateGyro_Closure)
                 (const Insta360__Messages__CalibrateGyro *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__calibrate_gyro__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_calibrate_5fgyro_2eproto__INCLUDED */
