/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cancel_authorization.proto */

#ifndef PROTOBUF_C_cancel_5fauthorization_2eproto__INCLUDED
#define PROTOBUF_C_cancel_5fauthorization_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__CancelAuthorization Insta360__Messages__CancelAuthorization;
typedef struct Insta360__Messages__CancelAuthorizationResp Insta360__Messages__CancelAuthorizationResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__CancelAuthorization
{
  ProtobufCMessage base;
};
#define INSTA360__MESSAGES__CANCEL_AUTHORIZATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__cancel_authorization__descriptor) \
     }


struct  Insta360__Messages__CancelAuthorizationResp
{
  ProtobufCMessage base;
};
#define INSTA360__MESSAGES__CANCEL_AUTHORIZATION_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__cancel_authorization_resp__descriptor) \
     }


/* Insta360__Messages__CancelAuthorization methods */
void   insta360__messages__cancel_authorization__init
                     (Insta360__Messages__CancelAuthorization         *message);
size_t insta360__messages__cancel_authorization__get_packed_size
                     (const Insta360__Messages__CancelAuthorization   *message);
size_t insta360__messages__cancel_authorization__pack
                     (const Insta360__Messages__CancelAuthorization   *message,
                      uint8_t             *out);
size_t insta360__messages__cancel_authorization__pack_to_buffer
                     (const Insta360__Messages__CancelAuthorization   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__CancelAuthorization *
       insta360__messages__cancel_authorization__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__cancel_authorization__free_unpacked
                     (Insta360__Messages__CancelAuthorization *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__CancelAuthorizationResp methods */
void   insta360__messages__cancel_authorization_resp__init
                     (Insta360__Messages__CancelAuthorizationResp         *message);
size_t insta360__messages__cancel_authorization_resp__get_packed_size
                     (const Insta360__Messages__CancelAuthorizationResp   *message);
size_t insta360__messages__cancel_authorization_resp__pack
                     (const Insta360__Messages__CancelAuthorizationResp   *message,
                      uint8_t             *out);
size_t insta360__messages__cancel_authorization_resp__pack_to_buffer
                     (const Insta360__Messages__CancelAuthorizationResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__CancelAuthorizationResp *
       insta360__messages__cancel_authorization_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__cancel_authorization_resp__free_unpacked
                     (Insta360__Messages__CancelAuthorizationResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__CancelAuthorization_Closure)
                 (const Insta360__Messages__CancelAuthorization *message,
                  void *closure_data);
typedef void (*Insta360__Messages__CancelAuthorizationResp_Closure)
                 (const Insta360__Messages__CancelAuthorizationResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__cancel_authorization__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__cancel_authorization_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_cancel_5fauthorization_2eproto__INCLUDED */
