/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: capture_auto_split.proto */

#ifndef PROTOBUF_C_capture_5fauto_5fsplit_2eproto__INCLUDED
#define PROTOBUF_C_capture_5fauto_5fsplit_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "video.pb-c.h"

typedef struct Insta360__Messages__NotificationCaptureAutoSplit Insta360__Messages__NotificationCaptureAutoSplit;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__NotificationCaptureAutoSplit
{
  ProtobufCMessage base;
  Insta360__Messages__Video *video;
};
#define INSTA360__MESSAGES__NOTIFICATION_CAPTURE_AUTO_SPLIT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__notification_capture_auto_split__descriptor) \
    , NULL }


/* Insta360__Messages__NotificationCaptureAutoSplit methods */
void   insta360__messages__notification_capture_auto_split__init
                     (Insta360__Messages__NotificationCaptureAutoSplit         *message);
size_t insta360__messages__notification_capture_auto_split__get_packed_size
                     (const Insta360__Messages__NotificationCaptureAutoSplit   *message);
size_t insta360__messages__notification_capture_auto_split__pack
                     (const Insta360__Messages__NotificationCaptureAutoSplit   *message,
                      uint8_t             *out);
size_t insta360__messages__notification_capture_auto_split__pack_to_buffer
                     (const Insta360__Messages__NotificationCaptureAutoSplit   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__NotificationCaptureAutoSplit *
       insta360__messages__notification_capture_auto_split__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__notification_capture_auto_split__free_unpacked
                     (Insta360__Messages__NotificationCaptureAutoSplit *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__NotificationCaptureAutoSplit_Closure)
                 (const Insta360__Messages__NotificationCaptureAutoSplit *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__notification_capture_auto_split__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_capture_5fauto_5fsplit_2eproto__INCLUDED */
