/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: capture_stopped.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "capture_stopped.pb-c.h"
void   insta360__messages__notification_capture_stopped__init
                     (Insta360__Messages__NotificationCaptureStopped         *message)
{
  static const Insta360__Messages__NotificationCaptureStopped init_value = INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__INIT;
  *message = init_value;
}
size_t insta360__messages__notification_capture_stopped__get_packed_size
                     (const Insta360__Messages__NotificationCaptureStopped *message)
{
  assert(message->base.descriptor == &insta360__messages__notification_capture_stopped__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__notification_capture_stopped__pack
                     (const Insta360__Messages__NotificationCaptureStopped *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__notification_capture_stopped__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__notification_capture_stopped__pack_to_buffer
                     (const Insta360__Messages__NotificationCaptureStopped *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__notification_capture_stopped__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__NotificationCaptureStopped *
       insta360__messages__notification_capture_stopped__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__NotificationCaptureStopped *)
     protobuf_c_message_unpack (&insta360__messages__notification_capture_stopped__descriptor,
                                allocator, len, data);
}
void   insta360__messages__notification_capture_stopped__free_unpacked
                     (Insta360__Messages__NotificationCaptureStopped *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__notification_capture_stopped__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue insta360__messages__notification_capture_stopped__error_code__enum_values_by_number[7] =
{
  { "OVER_TIME_LIMIT", "INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__OVER_TIME_LIMIT", 0 },
  { "STORAGE_FULL", "INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__STORAGE_FULL", 1 },
  { "OTHER_SITUATION", "INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__OTHER_SITUATION", 2 },
  { "OVER_FILE_NUMBER_LIMIT", "INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__OVER_FILE_NUMBER_LIMIT", 3 },
  { "LOW_CARD_SPEED", "INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__LOW_CARD_SPEED", 4 },
  { "MUXER_STREAM_ERROR", "INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__MUXER_STREAM_ERROR", 5 },
  { "DROP_FRAMES", "INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__DROP_FRAMES", 6 },
};
static const ProtobufCIntRange insta360__messages__notification_capture_stopped__error_code__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex insta360__messages__notification_capture_stopped__error_code__enum_values_by_name[7] =
{
  { "DROP_FRAMES", 6 },
  { "LOW_CARD_SPEED", 4 },
  { "MUXER_STREAM_ERROR", 5 },
  { "OTHER_SITUATION", 2 },
  { "OVER_FILE_NUMBER_LIMIT", 3 },
  { "OVER_TIME_LIMIT", 0 },
  { "STORAGE_FULL", 1 },
};
const ProtobufCEnumDescriptor insta360__messages__notification_capture_stopped__error_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.NotificationCaptureStopped.ErrorCode",
  "ErrorCode",
  "Insta360__Messages__NotificationCaptureStopped__ErrorCode",
  "insta360.messages",
  7,
  insta360__messages__notification_capture_stopped__error_code__enum_values_by_number,
  7,
  insta360__messages__notification_capture_stopped__error_code__enum_values_by_name,
  1,
  insta360__messages__notification_capture_stopped__error_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor insta360__messages__notification_capture_stopped__field_descriptors[2] =
{
  {
    "err_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__NotificationCaptureStopped, err_code),
    &insta360__messages__notification_capture_stopped__error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__NotificationCaptureStopped, video),
    &insta360__messages__video__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__notification_capture_stopped__field_indices_by_name[] = {
  0,   /* field[0] = err_code */
  1,   /* field[1] = video */
};
static const ProtobufCIntRange insta360__messages__notification_capture_stopped__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__notification_capture_stopped__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.NotificationCaptureStopped",
  "NotificationCaptureStopped",
  "Insta360__Messages__NotificationCaptureStopped",
  "insta360.messages",
  sizeof(Insta360__Messages__NotificationCaptureStopped),
  2,
  insta360__messages__notification_capture_stopped__field_descriptors,
  insta360__messages__notification_capture_stopped__field_indices_by_name,
  1,  insta360__messages__notification_capture_stopped__number_ranges,
  (ProtobufCMessageInit) insta360__messages__notification_capture_stopped__init,
  NULL,NULL,NULL    /* reserved[123] */
};
