/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: capture_auto_split.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "capture_auto_split.pb-c.h"
void   insta360__messages__notification_capture_auto_split__init
                     (Insta360__Messages__NotificationCaptureAutoSplit         *message)
{
  static const Insta360__Messages__NotificationCaptureAutoSplit init_value = INSTA360__MESSAGES__NOTIFICATION_CAPTURE_AUTO_SPLIT__INIT;
  *message = init_value;
}
size_t insta360__messages__notification_capture_auto_split__get_packed_size
                     (const Insta360__Messages__NotificationCaptureAutoSplit *message)
{
  assert(message->base.descriptor == &insta360__messages__notification_capture_auto_split__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__notification_capture_auto_split__pack
                     (const Insta360__Messages__NotificationCaptureAutoSplit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__notification_capture_auto_split__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__notification_capture_auto_split__pack_to_buffer
                     (const Insta360__Messages__NotificationCaptureAutoSplit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__notification_capture_auto_split__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__NotificationCaptureAutoSplit *
       insta360__messages__notification_capture_auto_split__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__NotificationCaptureAutoSplit *)
     protobuf_c_message_unpack (&insta360__messages__notification_capture_auto_split__descriptor,
                                allocator, len, data);
}
void   insta360__messages__notification_capture_auto_split__free_unpacked
                     (Insta360__Messages__NotificationCaptureAutoSplit *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__notification_capture_auto_split__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__notification_capture_auto_split__field_descriptors[1] =
{
  {
    "video",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__NotificationCaptureAutoSplit, video),
    &insta360__messages__video__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__notification_capture_auto_split__field_indices_by_name[] = {
  0,   /* field[0] = video */
};
static const ProtobufCIntRange insta360__messages__notification_capture_auto_split__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__notification_capture_auto_split__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.NotificationCaptureAutoSplit",
  "NotificationCaptureAutoSplit",
  "Insta360__Messages__NotificationCaptureAutoSplit",
  "insta360.messages",
  sizeof(Insta360__Messages__NotificationCaptureAutoSplit),
  1,
  insta360__messages__notification_capture_auto_split__field_descriptors,
  insta360__messages__notification_capture_auto_split__field_indices_by_name,
  1,  insta360__messages__notification_capture_auto_split__number_ranges,
  (ProtobufCMessageInit) insta360__messages__notification_capture_auto_split__init,
  NULL,NULL,NULL    /* reserved[123] */
};
