/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: capture_stopped.proto */

#ifndef PROTOBUF_C_capture_5fstopped_2eproto__INCLUDED
#define PROTOBUF_C_capture_5fstopped_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "video.pb-c.h"

typedef struct Insta360__Messages__NotificationCaptureStopped Insta360__Messages__NotificationCaptureStopped;


/* --- enums --- */

typedef enum _Insta360__Messages__NotificationCaptureStopped__ErrorCode {
  INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__OVER_TIME_LIMIT = 0,
  INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__STORAGE_FULL = 1,
  INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__OTHER_SITUATION = 2,
  INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__OVER_FILE_NUMBER_LIMIT = 3,
  INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__LOW_CARD_SPEED = 4,
  INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__MUXER_STREAM_ERROR = 5,
  INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__DROP_FRAMES = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE)
} Insta360__Messages__NotificationCaptureStopped__ErrorCode;

/* --- messages --- */

struct  Insta360__Messages__NotificationCaptureStopped
{
  ProtobufCMessage base;
  Insta360__Messages__NotificationCaptureStopped__ErrorCode err_code;
  Insta360__Messages__Video *video;
};
#define INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__notification_capture_stopped__descriptor) \
    , INSTA360__MESSAGES__NOTIFICATION_CAPTURE_STOPPED__ERROR_CODE__OVER_TIME_LIMIT, NULL }


/* Insta360__Messages__NotificationCaptureStopped methods */
void   insta360__messages__notification_capture_stopped__init
                     (Insta360__Messages__NotificationCaptureStopped         *message);
size_t insta360__messages__notification_capture_stopped__get_packed_size
                     (const Insta360__Messages__NotificationCaptureStopped   *message);
size_t insta360__messages__notification_capture_stopped__pack
                     (const Insta360__Messages__NotificationCaptureStopped   *message,
                      uint8_t             *out);
size_t insta360__messages__notification_capture_stopped__pack_to_buffer
                     (const Insta360__Messages__NotificationCaptureStopped   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__NotificationCaptureStopped *
       insta360__messages__notification_capture_stopped__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__notification_capture_stopped__free_unpacked
                     (Insta360__Messages__NotificationCaptureStopped *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__NotificationCaptureStopped_Closure)
                 (const Insta360__Messages__NotificationCaptureStopped *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__notification_capture_stopped__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__notification_capture_stopped__error_code__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_capture_5fstopped_2eproto__INCLUDED */
