/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: capture_state.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "capture_state.pb-c.h"
static const ProtobufCEnumValue insta360__messages__camera_capture_state__enum_values_by_number[11] =
{
  { "NOT_CAPTURE", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__NOT_CAPTURE", 0 },
  { "NORMAL_CAPTURE", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__NORMAL_CAPTURE", 1 },
  { "TIMELAPSE_CAPTURE", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__TIMELAPSE_CAPTURE", 2 },
  { "INTERVAL_SHOOTING_CAPTURE", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__INTERVAL_SHOOTING_CAPTURE", 3 },
  { "SINGLE_SHOOTING", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__SINGLE_SHOOTING", 4 },
  { "HDR_SHOOTING", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__HDR_SHOOTING", 5 },
  { "SELF_TIMER_SHOOTING", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__SELF_TIMER_SHOOTING", 6 },
  { "BULLET_TIME_CAPTURE", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__BULLET_TIME_CAPTURE", 7 },
  { "SETTINGS_NEW_VALUE", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__SETTINGS_NEW_VALUE", 8 },
  { "HDR_CAPTURE", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__HDR_CAPTURE", 9 },
  { "BURST_SHOOTING", "INSTA360__MESSAGES__CAMERA_CAPTURE_STATE__BURST_SHOOTING", 10 },
};
static const ProtobufCIntRange insta360__messages__camera_capture_state__value_ranges[] = {
{0, 0},{0, 11}
};
static const ProtobufCEnumValueIndex insta360__messages__camera_capture_state__enum_values_by_name[11] =
{
  { "BULLET_TIME_CAPTURE", 7 },
  { "BURST_SHOOTING", 10 },
  { "HDR_CAPTURE", 9 },
  { "HDR_SHOOTING", 5 },
  { "INTERVAL_SHOOTING_CAPTURE", 3 },
  { "NORMAL_CAPTURE", 1 },
  { "NOT_CAPTURE", 0 },
  { "SELF_TIMER_SHOOTING", 6 },
  { "SETTINGS_NEW_VALUE", 8 },
  { "SINGLE_SHOOTING", 4 },
  { "TIMELAPSE_CAPTURE", 2 },
};
const ProtobufCEnumDescriptor insta360__messages__camera_capture_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.CameraCaptureState",
  "CameraCaptureState",
  "Insta360__Messages__CameraCaptureState",
  "insta360.messages",
  11,
  insta360__messages__camera_capture_state__enum_values_by_number,
  11,
  insta360__messages__camera_capture_state__enum_values_by_name,
  1,
  insta360__messages__camera_capture_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
