/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: close_camera_oled.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "close_camera_oled.pb-c.h"
void   insta360__messages__close_camera_oled__init
                     (Insta360__Messages__CloseCameraOled         *message)
{
  static const Insta360__Messages__CloseCameraOled init_value = INSTA360__MESSAGES__CLOSE_CAMERA_OLED__INIT;
  *message = init_value;
}
size_t insta360__messages__close_camera_oled__get_packed_size
                     (const Insta360__Messages__CloseCameraOled *message)
{
  assert(message->base.descriptor == &insta360__messages__close_camera_oled__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__close_camera_oled__pack
                     (const Insta360__Messages__CloseCameraOled *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__close_camera_oled__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__close_camera_oled__pack_to_buffer
                     (const Insta360__Messages__CloseCameraOled *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__close_camera_oled__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__CloseCameraOled *
       insta360__messages__close_camera_oled__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__CloseCameraOled *)
     protobuf_c_message_unpack (&insta360__messages__close_camera_oled__descriptor,
                                allocator, len, data);
}
void   insta360__messages__close_camera_oled__free_unpacked
                     (Insta360__Messages__CloseCameraOled *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__close_camera_oled__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__close_camera_oled_resp__init
                     (Insta360__Messages__CloseCameraOledResp         *message)
{
  static const Insta360__Messages__CloseCameraOledResp init_value = INSTA360__MESSAGES__CLOSE_CAMERA_OLED_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__close_camera_oled_resp__get_packed_size
                     (const Insta360__Messages__CloseCameraOledResp *message)
{
  assert(message->base.descriptor == &insta360__messages__close_camera_oled_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__close_camera_oled_resp__pack
                     (const Insta360__Messages__CloseCameraOledResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__close_camera_oled_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__close_camera_oled_resp__pack_to_buffer
                     (const Insta360__Messages__CloseCameraOledResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__close_camera_oled_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__CloseCameraOledResp *
       insta360__messages__close_camera_oled_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__CloseCameraOledResp *)
     protobuf_c_message_unpack (&insta360__messages__close_camera_oled_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__close_camera_oled_resp__free_unpacked
                     (Insta360__Messages__CloseCameraOledResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__close_camera_oled_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define insta360__messages__close_camera_oled__field_descriptors NULL
#define insta360__messages__close_camera_oled__field_indices_by_name NULL
#define insta360__messages__close_camera_oled__number_ranges NULL
const ProtobufCMessageDescriptor insta360__messages__close_camera_oled__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.CloseCameraOled",
  "CloseCameraOled",
  "Insta360__Messages__CloseCameraOled",
  "insta360.messages",
  sizeof(Insta360__Messages__CloseCameraOled),
  0,
  insta360__messages__close_camera_oled__field_descriptors,
  insta360__messages__close_camera_oled__field_indices_by_name,
  0,  insta360__messages__close_camera_oled__number_ranges,
  (ProtobufCMessageInit) insta360__messages__close_camera_oled__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define insta360__messages__close_camera_oled_resp__field_descriptors NULL
#define insta360__messages__close_camera_oled_resp__field_indices_by_name NULL
#define insta360__messages__close_camera_oled_resp__number_ranges NULL
const ProtobufCMessageDescriptor insta360__messages__close_camera_oled_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.CloseCameraOledResp",
  "CloseCameraOledResp",
  "Insta360__Messages__CloseCameraOledResp",
  "insta360.messages",
  sizeof(Insta360__Messages__CloseCameraOledResp),
  0,
  insta360__messages__close_camera_oled_resp__field_descriptors,
  insta360__messages__close_camera_oled_resp__field_indices_by_name,
  0,  insta360__messages__close_camera_oled_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__close_camera_oled_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
