/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: delete_files.proto */

#ifndef PROTOBUF_C_delete_5ffiles_2eproto__INCLUDED
#define PROTOBUF_C_delete_5ffiles_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__DeleteFiles Insta360__Messages__DeleteFiles;
typedef struct Insta360__Messages__DeleteFilesResp Insta360__Messages__DeleteFilesResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__DeleteFiles
{
  ProtobufCMessage base;
  size_t n_uri;
  char **uri;
};
#define INSTA360__MESSAGES__DELETE_FILES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__delete_files__descriptor) \
    , 0,NULL }


struct  Insta360__Messages__DeleteFilesResp
{
  ProtobufCMessage base;
  size_t n_fail_uri;
  char **fail_uri;
};
#define INSTA360__MESSAGES__DELETE_FILES_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__delete_files_resp__descriptor) \
    , 0,NULL }


/* Insta360__Messages__DeleteFiles methods */
void   insta360__messages__delete_files__init
                     (Insta360__Messages__DeleteFiles         *message);
size_t insta360__messages__delete_files__get_packed_size
                     (const Insta360__Messages__DeleteFiles   *message);
size_t insta360__messages__delete_files__pack
                     (const Insta360__Messages__DeleteFiles   *message,
                      uint8_t             *out);
size_t insta360__messages__delete_files__pack_to_buffer
                     (const Insta360__Messages__DeleteFiles   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__DeleteFiles *
       insta360__messages__delete_files__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__delete_files__free_unpacked
                     (Insta360__Messages__DeleteFiles *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__DeleteFilesResp methods */
void   insta360__messages__delete_files_resp__init
                     (Insta360__Messages__DeleteFilesResp         *message);
size_t insta360__messages__delete_files_resp__get_packed_size
                     (const Insta360__Messages__DeleteFilesResp   *message);
size_t insta360__messages__delete_files_resp__pack
                     (const Insta360__Messages__DeleteFilesResp   *message,
                      uint8_t             *out);
size_t insta360__messages__delete_files_resp__pack_to_buffer
                     (const Insta360__Messages__DeleteFilesResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__DeleteFilesResp *
       insta360__messages__delete_files_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__delete_files_resp__free_unpacked
                     (Insta360__Messages__DeleteFilesResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__DeleteFiles_Closure)
                 (const Insta360__Messages__DeleteFiles *message,
                  void *closure_data);
typedef void (*Insta360__Messages__DeleteFilesResp_Closure)
                 (const Insta360__Messages__DeleteFilesResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__delete_files__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__delete_files_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_delete_5ffiles_2eproto__INCLUDED */
