/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: delete_files.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "delete_files.pb-c.h"
void   insta360__messages__delete_files__init
                     (Insta360__Messages__DeleteFiles         *message)
{
  static const Insta360__Messages__DeleteFiles init_value = INSTA360__MESSAGES__DELETE_FILES__INIT;
  *message = init_value;
}
size_t insta360__messages__delete_files__get_packed_size
                     (const Insta360__Messages__DeleteFiles *message)
{
  assert(message->base.descriptor == &insta360__messages__delete_files__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__delete_files__pack
                     (const Insta360__Messages__DeleteFiles *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__delete_files__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__delete_files__pack_to_buffer
                     (const Insta360__Messages__DeleteFiles *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__delete_files__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__DeleteFiles *
       insta360__messages__delete_files__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__DeleteFiles *)
     protobuf_c_message_unpack (&insta360__messages__delete_files__descriptor,
                                allocator, len, data);
}
void   insta360__messages__delete_files__free_unpacked
                     (Insta360__Messages__DeleteFiles *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__delete_files__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__delete_files_resp__init
                     (Insta360__Messages__DeleteFilesResp         *message)
{
  static const Insta360__Messages__DeleteFilesResp init_value = INSTA360__MESSAGES__DELETE_FILES_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__delete_files_resp__get_packed_size
                     (const Insta360__Messages__DeleteFilesResp *message)
{
  assert(message->base.descriptor == &insta360__messages__delete_files_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__delete_files_resp__pack
                     (const Insta360__Messages__DeleteFilesResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__delete_files_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__delete_files_resp__pack_to_buffer
                     (const Insta360__Messages__DeleteFilesResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__delete_files_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__DeleteFilesResp *
       insta360__messages__delete_files_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__DeleteFilesResp *)
     protobuf_c_message_unpack (&insta360__messages__delete_files_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__delete_files_resp__free_unpacked
                     (Insta360__Messages__DeleteFilesResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__delete_files_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__delete_files__field_descriptors[1] =
{
  {
    "uri",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Insta360__Messages__DeleteFiles, n_uri),
    offsetof(Insta360__Messages__DeleteFiles, uri),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__delete_files__field_indices_by_name[] = {
  0,   /* field[0] = uri */
};
static const ProtobufCIntRange insta360__messages__delete_files__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__delete_files__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.DeleteFiles",
  "DeleteFiles",
  "Insta360__Messages__DeleteFiles",
  "insta360.messages",
  sizeof(Insta360__Messages__DeleteFiles),
  1,
  insta360__messages__delete_files__field_descriptors,
  insta360__messages__delete_files__field_indices_by_name,
  1,  insta360__messages__delete_files__number_ranges,
  (ProtobufCMessageInit) insta360__messages__delete_files__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__delete_files_resp__field_descriptors[1] =
{
  {
    "fail_uri",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Insta360__Messages__DeleteFilesResp, n_fail_uri),
    offsetof(Insta360__Messages__DeleteFilesResp, fail_uri),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__delete_files_resp__field_indices_by_name[] = {
  0,   /* field[0] = fail_uri */
};
static const ProtobufCIntRange insta360__messages__delete_files_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__delete_files_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.DeleteFilesResp",
  "DeleteFilesResp",
  "Insta360__Messages__DeleteFilesResp",
  "insta360.messages",
  sizeof(Insta360__Messages__DeleteFilesResp),
  1,
  insta360__messages__delete_files_resp__field_descriptors,
  insta360__messages__delete_files_resp__field_indices_by_name,
  1,  insta360__messages__delete_files_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__delete_files_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
