/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: error.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "error.pb-c.h"
void   insta360__messages__error__init
                     (Insta360__Messages__Error         *message)
{
  static const Insta360__Messages__Error init_value = INSTA360__MESSAGES__ERROR__INIT;
  *message = init_value;
}
size_t insta360__messages__error__get_packed_size
                     (const Insta360__Messages__Error *message)
{
  assert(message->base.descriptor == &insta360__messages__error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__error__pack
                     (const Insta360__Messages__Error *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__error__pack_to_buffer
                     (const Insta360__Messages__Error *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__Error *
       insta360__messages__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__Error *)
     protobuf_c_message_unpack (&insta360__messages__error__descriptor,
                                allocator, len, data);
}
void   insta360__messages__error__free_unpacked
                     (Insta360__Messages__Error *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue insta360__messages__error__error_code__enum_values_by_number[5] =
{
  { "UNKNOWN_ERROR", "INSTA360__MESSAGES__ERROR__ERROR_CODE__UNKNOWN_ERROR", 0 },
  { "UNKNOWN_MSG_CODE", "INSTA360__MESSAGES__ERROR__ERROR_CODE__UNKNOWN_MSG_CODE", 1 },
  { "UNKNOWN_MSG_PAYLOAD", "INSTA360__MESSAGES__ERROR__ERROR_CODE__UNKNOWN_MSG_PAYLOAD", 2 },
  { "EXECUTE_ERROR", "INSTA360__MESSAGES__ERROR__ERROR_CODE__EXECUTE_ERROR", 3 },
  { "OVER_FILE_NUMBER_LIMIT", "INSTA360__MESSAGES__ERROR__ERROR_CODE__OVER_FILE_NUMBER_LIMIT", 4 },
};
static const ProtobufCIntRange insta360__messages__error__error_code__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex insta360__messages__error__error_code__enum_values_by_name[5] =
{
  { "EXECUTE_ERROR", 3 },
  { "OVER_FILE_NUMBER_LIMIT", 4 },
  { "UNKNOWN_ERROR", 0 },
  { "UNKNOWN_MSG_CODE", 1 },
  { "UNKNOWN_MSG_PAYLOAD", 2 },
};
const ProtobufCEnumDescriptor insta360__messages__error__error_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.Error.ErrorCode",
  "ErrorCode",
  "Insta360__Messages__Error__ErrorCode",
  "insta360.messages",
  5,
  insta360__messages__error__error_code__enum_values_by_number,
  5,
  insta360__messages__error__error_code__enum_values_by_name,
  1,
  insta360__messages__error__error_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor insta360__messages__error__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Error, code),
    &insta360__messages__error__error_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Error, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__error__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = message */
};
static const ProtobufCIntRange insta360__messages__error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.Error",
  "Error",
  "Insta360__Messages__Error",
  "insta360.messages",
  sizeof(Insta360__Messages__Error),
  2,
  insta360__messages__error__field_descriptors,
  insta360__messages__error__field_indices_by_name,
  1,  insta360__messages__error__number_ranges,
  (ProtobufCMessageInit) insta360__messages__error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
