/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: extra_info.proto */

#ifndef PROTOBUF_C_extra_5finfo_2eproto__INCLUDED
#define PROTOBUF_C_extra_5finfo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__ExtraMetadata Insta360__Messages__ExtraMetadata;
typedef struct Insta360__Messages__ExtraMetadata__ExtraUserOptions Insta360__Messages__ExtraMetadata__ExtraUserOptions;
typedef struct Insta360__Messages__ExtraMetadata__Vector2 Insta360__Messages__ExtraMetadata__Vector2;
typedef struct Insta360__Messages__ExtraMetadata__GyroIndex Insta360__Messages__ExtraMetadata__GyroIndex;
typedef struct Insta360__Messages__ExtraMetadata__FileGroupInfo Insta360__Messages__ExtraMetadata__FileGroupInfo;
typedef struct Insta360__Messages__ExtraMetadata__WindowCropInfo Insta360__Messages__ExtraMetadata__WindowCropInfo;


/* --- enums --- */

typedef enum _Insta360__Messages__ExtraMetadata__ExtraUserOptions__LogoType {
  INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__LOGO_TYPE__UNKNOWN_LOGO_TYPE = 0,
  INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__LOGO_TYPE__NO_LOGO = 1,
  INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__LOGO_TYPE__INSTA_LOGO = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__LOGO_TYPE)
} Insta360__Messages__ExtraMetadata__ExtraUserOptions__LogoType;
typedef enum _Insta360__Messages__ExtraMetadata__ExtraUserOptions__OffsetConvertState {
  INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__OFFSET_CONVERT_STATE__WaterProof = 0,
  INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__OFFSET_CONVERT_STATE__DivingWater = 1,
  INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__OFFSET_CONVERT_STATE__DivingAir = 2,
  INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__OFFSET_CONVERT_STATE__StitchOptimization = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__OFFSET_CONVERT_STATE)
} Insta360__Messages__ExtraMetadata__ExtraUserOptions__OffsetConvertState;
typedef enum _Insta360__Messages__ExtraMetadata__HDRSTATE {
  INSTA360__MESSAGES__EXTRA_METADATA__HDR__STATE__NOT_HDR = 0,
  INSTA360__MESSAGES__EXTRA_METADATA__HDR__STATE__WAITING_PROCESS = 1,
  INSTA360__MESSAGES__EXTRA_METADATA__HDR__STATE__PROCESSED = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__EXTRA_METADATA__HDR__STATE)
} Insta360__Messages__ExtraMetadata__HDRSTATE;
typedef enum _Insta360__Messages__ExtraMetadata__TriggerSource {
  INSTA360__MESSAGES__EXTRA_METADATA__TRIGGER_SOURCE__Unknown = 0,
  INSTA360__MESSAGES__EXTRA_METADATA__TRIGGER_SOURCE__CameraButton = 1,
  INSTA360__MESSAGES__EXTRA_METADATA__TRIGGER_SOURCE__RemoteControl = 2,
  INSTA360__MESSAGES__EXTRA_METADATA__TRIGGER_SOURCE__USB = 3,
  INSTA360__MESSAGES__EXTRA_METADATA__TRIGGER_SOURCE__BtRemote = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__EXTRA_METADATA__TRIGGER_SOURCE)
} Insta360__Messages__ExtraMetadata__TriggerSource;
typedef enum _Insta360__Messages__ExtraMetadata__EvoStatusMode {
  INSTA360__MESSAGES__EXTRA_METADATA__EVO_STATUS_MODE__UNKNOWN_STATUS_MODE = 0,
  INSTA360__MESSAGES__EXTRA_METADATA__EVO_STATUS_MODE__DEGREE180 = 1,
  INSTA360__MESSAGES__EXTRA_METADATA__EVO_STATUS_MODE__DEGREE360 = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__EXTRA_METADATA__EVO_STATUS_MODE)
} Insta360__Messages__ExtraMetadata__EvoStatusMode;
typedef enum _Insta360__Messages__ExtraMetadata__GpsSource {
  INSTA360__MESSAGES__EXTRA_METADATA__GPS_SOURCE__GSV = 0,
  INSTA360__MESSAGES__EXTRA_METADATA__GPS_SOURCE__DASHBOARD = 1,
  INSTA360__MESSAGES__EXTRA_METADATA__GPS_SOURCE__REMOTE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__EXTRA_METADATA__GPS_SOURCE)
} Insta360__Messages__ExtraMetadata__GpsSource;
typedef enum _Insta360__Messages__ExtraMetadata__SubMediaType {
  INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE__VIDEO_NORMAL = 0,
  INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE__VIDEO_BULLETTIME = 1,
  INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE__VIDEO_TIMELAPSE = 2,
  INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE__PHOTO_NORMAL = 3,
  INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE__PHOTO_HDR = 4,
  INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE__PHOTO_INTERVALSHOOTING = 5,
  INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE__VIDEO_HDR = 6,
  INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE__PHOTO_BURST = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE)
} Insta360__Messages__ExtraMetadata__SubMediaType;
typedef enum _Insta360__Messages__ExtraType {
  INSTA360__MESSAGES__EXTRA_TYPE__EXTRA_TYPE_ALL = 0,
  INSTA360__MESSAGES__EXTRA_TYPE__EXTRA_TYPE_METADATA = 1,
  INSTA360__MESSAGES__EXTRA_TYPE__EXTRA_TYPE_THUMBNAIL = 2,
  INSTA360__MESSAGES__EXTRA_TYPE__EXTRA_TYPE_GYRO = 3,
  INSTA360__MESSAGES__EXTRA_TYPE__EXTRA_TYPE_EXPOSURE = 4,
  INSTA360__MESSAGES__EXTRA_TYPE__EXTRA_TYPE_EXT_THUMBNAIL = 5,
  INSTA360__MESSAGES__EXTRA_TYPE__EXTRA_TYPE_FRAME_PTS = 6,
  INSTA360__MESSAGES__EXTRA_TYPE__EXTRA_TYPE_GPS = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__EXTRA_TYPE)
} Insta360__Messages__ExtraType;

/* --- messages --- */

struct  Insta360__Messages__ExtraMetadata__ExtraUserOptions
{
  ProtobufCMessage base;
  char *filter;
  char *befilter;
  ProtobufCBinaryData euler;
  protobuf_c_boolean rm_purple;
  uint32_t gyro_calibrate_mode;
  protobuf_c_boolean euler_enable;
  Insta360__Messages__ExtraMetadata__ExtraUserOptions__LogoType logo_type;
  char *adjustfilters;
  char *lut_filter;
  size_t n_offset_convert_states;
  Insta360__Messages__ExtraMetadata__ExtraUserOptions__OffsetConvertState *offset_convert_states;
};
#define INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__extra_metadata__extra_user_options__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, 0, 0, 0, INSTA360__MESSAGES__EXTRA_METADATA__EXTRA_USER_OPTIONS__LOGO_TYPE__UNKNOWN_LOGO_TYPE, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  Insta360__Messages__ExtraMetadata__Vector2
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
};
#define INSTA360__MESSAGES__EXTRA_METADATA__VECTOR2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__extra_metadata__vector2__descriptor) \
    , 0, 0 }


struct  Insta360__Messages__ExtraMetadata__GyroIndex
{
  ProtobufCMessage base;
  int32_t index;
  int64_t timestamp;
};
#define INSTA360__MESSAGES__EXTRA_METADATA__GYRO_INDEX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__extra_metadata__gyro_index__descriptor) \
    , 0, 0 }


struct  Insta360__Messages__ExtraMetadata__FileGroupInfo
{
  ProtobufCMessage base;
  Insta360__Messages__ExtraMetadata__SubMediaType type;
  uint32_t index;
  char *identify;
};
#define INSTA360__MESSAGES__EXTRA_METADATA__FILE_GROUP_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__extra_metadata__file_group_info__descriptor) \
    , INSTA360__MESSAGES__EXTRA_METADATA__SUB_MEDIA_TYPE__VIDEO_NORMAL, 0, (char *)protobuf_c_empty_string }


struct  Insta360__Messages__ExtraMetadata__WindowCropInfo
{
  ProtobufCMessage base;
  uint32_t src_width;
  uint32_t src_height;
  uint32_t dst_width;
  uint32_t dst_height;
};
#define INSTA360__MESSAGES__EXTRA_METADATA__WINDOW_CROP_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__extra_metadata__window_crop_info__descriptor) \
    , 0, 0, 0, 0 }


struct  Insta360__Messages__ExtraMetadata
{
  ProtobufCMessage base;
  char *serial_number;
  char *camera_type;
  char *fw_version;
  char *file_type;
  char *offset;
  char *ip;
  uint64_t creation_time;
  uint64_t export_time;
  uint64_t file_size;
  uint32_t total_time;
  ProtobufCBinaryData gps;
  ProtobufCBinaryData orientation;
  Insta360__Messages__ExtraMetadata__ExtraUserOptions *user_options;
  ProtobufCBinaryData gyro;
  Insta360__Messages__ExtraMetadata__HDRSTATE hdr_state;
  char *hdr_identifier;
  char *original_offset;
  Insta360__Messages__ExtraMetadata__TriggerSource trigger_source;
  Insta360__Messages__ExtraMetadata__Vector2 *dimension;
  int32_t frame_rate;
  Insta360__Messages__ExtraMetadata__Vector2 *image_translate;
  char *gamma_mode;
  Insta360__Messages__ExtraMetadata__GyroIndex *thumbnail_gyro_index;
  int64_t first_frame_timestamp;
  double rolling_shutter_time;
  Insta360__Messages__ExtraMetadata__FileGroupInfo *file_group_info;
  Insta360__Messages__ExtraMetadata__WindowCropInfo *window_crop_info;
  double gyro_timestamp;
  protobuf_c_boolean is_has_gyro_timestamp;
  uint32_t timelapse_interval;
  ProtobufCBinaryData gyro_calib;
  Insta360__Messages__ExtraMetadata__EvoStatusMode evo_status_mode;
  char *evo_status_id;
  char *original_offset_3d;
  size_t n_gps_sources;
  Insta360__Messages__ExtraMetadata__GpsSource *gps_sources;
  int64_t first_gps_timestamp;
};
#define INSTA360__MESSAGES__EXTRA_METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__extra_metadata__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, {0,NULL}, {0,NULL}, NULL, {0,NULL}, INSTA360__MESSAGES__EXTRA_METADATA__HDR__STATE__NOT_HDR, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, INSTA360__MESSAGES__EXTRA_METADATA__TRIGGER_SOURCE__Unknown, NULL, 0, NULL, (char *)protobuf_c_empty_string, NULL, 0, 0, NULL, NULL, 0, 0, 0, {0,NULL}, INSTA360__MESSAGES__EXTRA_METADATA__EVO_STATUS_MODE__UNKNOWN_STATUS_MODE, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0 }


/* Insta360__Messages__ExtraMetadata__ExtraUserOptions methods */
void   insta360__messages__extra_metadata__extra_user_options__init
                     (Insta360__Messages__ExtraMetadata__ExtraUserOptions         *message);
/* Insta360__Messages__ExtraMetadata__Vector2 methods */
void   insta360__messages__extra_metadata__vector2__init
                     (Insta360__Messages__ExtraMetadata__Vector2         *message);
/* Insta360__Messages__ExtraMetadata__GyroIndex methods */
void   insta360__messages__extra_metadata__gyro_index__init
                     (Insta360__Messages__ExtraMetadata__GyroIndex         *message);
/* Insta360__Messages__ExtraMetadata__FileGroupInfo methods */
void   insta360__messages__extra_metadata__file_group_info__init
                     (Insta360__Messages__ExtraMetadata__FileGroupInfo         *message);
/* Insta360__Messages__ExtraMetadata__WindowCropInfo methods */
void   insta360__messages__extra_metadata__window_crop_info__init
                     (Insta360__Messages__ExtraMetadata__WindowCropInfo         *message);
/* Insta360__Messages__ExtraMetadata methods */
void   insta360__messages__extra_metadata__init
                     (Insta360__Messages__ExtraMetadata         *message);
size_t insta360__messages__extra_metadata__get_packed_size
                     (const Insta360__Messages__ExtraMetadata   *message);
size_t insta360__messages__extra_metadata__pack
                     (const Insta360__Messages__ExtraMetadata   *message,
                      uint8_t             *out);
size_t insta360__messages__extra_metadata__pack_to_buffer
                     (const Insta360__Messages__ExtraMetadata   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__ExtraMetadata *
       insta360__messages__extra_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__extra_metadata__free_unpacked
                     (Insta360__Messages__ExtraMetadata *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__ExtraMetadata__ExtraUserOptions_Closure)
                 (const Insta360__Messages__ExtraMetadata__ExtraUserOptions *message,
                  void *closure_data);
typedef void (*Insta360__Messages__ExtraMetadata__Vector2_Closure)
                 (const Insta360__Messages__ExtraMetadata__Vector2 *message,
                  void *closure_data);
typedef void (*Insta360__Messages__ExtraMetadata__GyroIndex_Closure)
                 (const Insta360__Messages__ExtraMetadata__GyroIndex *message,
                  void *closure_data);
typedef void (*Insta360__Messages__ExtraMetadata__FileGroupInfo_Closure)
                 (const Insta360__Messages__ExtraMetadata__FileGroupInfo *message,
                  void *closure_data);
typedef void (*Insta360__Messages__ExtraMetadata__WindowCropInfo_Closure)
                 (const Insta360__Messages__ExtraMetadata__WindowCropInfo *message,
                  void *closure_data);
typedef void (*Insta360__Messages__ExtraMetadata_Closure)
                 (const Insta360__Messages__ExtraMetadata *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    insta360__messages__extra_type__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__extra_metadata__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__extra_metadata__extra_user_options__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__extra_metadata__extra_user_options__logo_type__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__extra_metadata__extra_user_options__offset_convert_state__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__extra_metadata__vector2__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__extra_metadata__gyro_index__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__extra_metadata__file_group_info__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__extra_metadata__window_crop_info__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__extra_metadata__hdr__state__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__extra_metadata__trigger_source__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__extra_metadata__evo_status_mode__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__extra_metadata__gps_source__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__extra_metadata__sub_media_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_extra_5finfo_2eproto__INCLUDED */
