/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fileinfo_list.proto */

#ifndef PROTOBUF_C_fileinfo_5flist_2eproto__INCLUDED
#define PROTOBUF_C_fileinfo_5flist_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__FileInfo Insta360__Messages__FileInfo;
typedef struct Insta360__Messages__FileInfoList Insta360__Messages__FileInfoList;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__FileInfo
{
  ProtobufCMessage base;
  char *file_path;
  ProtobufCBinaryData metadata;
};
#define INSTA360__MESSAGES__FILE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__file_info__descriptor) \
    , (char *)protobuf_c_empty_string, {0,NULL} }


struct  Insta360__Messages__FileInfoList
{
  ProtobufCMessage base;
  size_t n_file_info;
  Insta360__Messages__FileInfo **file_info;
};
#define INSTA360__MESSAGES__FILE_INFO__LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__file_info__list__descriptor) \
    , 0,NULL }


/* Insta360__Messages__FileInfo methods */
void   insta360__messages__file_info__init
                     (Insta360__Messages__FileInfo         *message);
size_t insta360__messages__file_info__get_packed_size
                     (const Insta360__Messages__FileInfo   *message);
size_t insta360__messages__file_info__pack
                     (const Insta360__Messages__FileInfo   *message,
                      uint8_t             *out);
size_t insta360__messages__file_info__pack_to_buffer
                     (const Insta360__Messages__FileInfo   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__FileInfo *
       insta360__messages__file_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__file_info__free_unpacked
                     (Insta360__Messages__FileInfo *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__FileInfoList methods */
void   insta360__messages__file_info__list__init
                     (Insta360__Messages__FileInfoList         *message);
size_t insta360__messages__file_info__list__get_packed_size
                     (const Insta360__Messages__FileInfoList   *message);
size_t insta360__messages__file_info__list__pack
                     (const Insta360__Messages__FileInfoList   *message,
                      uint8_t             *out);
size_t insta360__messages__file_info__list__pack_to_buffer
                     (const Insta360__Messages__FileInfoList   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__FileInfoList *
       insta360__messages__file_info__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__file_info__list__free_unpacked
                     (Insta360__Messages__FileInfoList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__FileInfo_Closure)
                 (const Insta360__Messages__FileInfo *message,
                  void *closure_data);
typedef void (*Insta360__Messages__FileInfoList_Closure)
                 (const Insta360__Messages__FileInfoList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__file_info__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__file_info__list__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_fileinfo_5flist_2eproto__INCLUDED */
