/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fileinfo_list.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "fileinfo_list.pb-c.h"
void   insta360__messages__file_info__init
                     (Insta360__Messages__FileInfo         *message)
{
  static const Insta360__Messages__FileInfo init_value = INSTA360__MESSAGES__FILE_INFO__INIT;
  *message = init_value;
}
size_t insta360__messages__file_info__get_packed_size
                     (const Insta360__Messages__FileInfo *message)
{
  assert(message->base.descriptor == &insta360__messages__file_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__file_info__pack
                     (const Insta360__Messages__FileInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__file_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__file_info__pack_to_buffer
                     (const Insta360__Messages__FileInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__file_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__FileInfo *
       insta360__messages__file_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__FileInfo *)
     protobuf_c_message_unpack (&insta360__messages__file_info__descriptor,
                                allocator, len, data);
}
void   insta360__messages__file_info__free_unpacked
                     (Insta360__Messages__FileInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__file_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__file_info__list__init
                     (Insta360__Messages__FileInfoList         *message)
{
  static const Insta360__Messages__FileInfoList init_value = INSTA360__MESSAGES__FILE_INFO__LIST__INIT;
  *message = init_value;
}
size_t insta360__messages__file_info__list__get_packed_size
                     (const Insta360__Messages__FileInfoList *message)
{
  assert(message->base.descriptor == &insta360__messages__file_info__list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__file_info__list__pack
                     (const Insta360__Messages__FileInfoList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__file_info__list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__file_info__list__pack_to_buffer
                     (const Insta360__Messages__FileInfoList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__file_info__list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__FileInfoList *
       insta360__messages__file_info__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__FileInfoList *)
     protobuf_c_message_unpack (&insta360__messages__file_info__list__descriptor,
                                allocator, len, data);
}
void   insta360__messages__file_info__list__free_unpacked
                     (Insta360__Messages__FileInfoList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__file_info__list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__file_info__field_descriptors[2] =
{
  {
    "file_path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__FileInfo, file_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__FileInfo, metadata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__file_info__field_indices_by_name[] = {
  0,   /* field[0] = file_path */
  1,   /* field[1] = metadata */
};
static const ProtobufCIntRange insta360__messages__file_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__file_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.FileInfo",
  "FileInfo",
  "Insta360__Messages__FileInfo",
  "insta360.messages",
  sizeof(Insta360__Messages__FileInfo),
  2,
  insta360__messages__file_info__field_descriptors,
  insta360__messages__file_info__field_indices_by_name,
  1,  insta360__messages__file_info__number_ranges,
  (ProtobufCMessageInit) insta360__messages__file_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__file_info__list__field_descriptors[1] =
{
  {
    "file_info",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Insta360__Messages__FileInfoList, n_file_info),
    offsetof(Insta360__Messages__FileInfoList, file_info),
    &insta360__messages__file_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__file_info__list__field_indices_by_name[] = {
  0,   /* field[0] = file_info */
};
static const ProtobufCIntRange insta360__messages__file_info__list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__file_info__list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.FileInfo_List",
  "FileInfoList",
  "Insta360__Messages__FileInfoList",
  "insta360.messages",
  sizeof(Insta360__Messages__FileInfoList),
  1,
  insta360__messages__file_info__list__field_descriptors,
  insta360__messages__file_info__list__field_indices_by_name,
  1,  insta360__messages__file_info__list__number_ranges,
  (ProtobufCMessageInit) insta360__messages__file_info__list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
