/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: get_timelapse_options.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "get_timelapse_options.pb-c.h"
void   insta360__messages__get_timelapse_options__init
                     (Insta360__Messages__GetTimelapseOptions         *message)
{
  static const Insta360__Messages__GetTimelapseOptions init_value = INSTA360__MESSAGES__GET_TIMELAPSE_OPTIONS__INIT;
  *message = init_value;
}
size_t insta360__messages__get_timelapse_options__get_packed_size
                     (const Insta360__Messages__GetTimelapseOptions *message)
{
  assert(message->base.descriptor == &insta360__messages__get_timelapse_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__get_timelapse_options__pack
                     (const Insta360__Messages__GetTimelapseOptions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__get_timelapse_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__get_timelapse_options__pack_to_buffer
                     (const Insta360__Messages__GetTimelapseOptions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__get_timelapse_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__GetTimelapseOptions *
       insta360__messages__get_timelapse_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__GetTimelapseOptions *)
     protobuf_c_message_unpack (&insta360__messages__get_timelapse_options__descriptor,
                                allocator, len, data);
}
void   insta360__messages__get_timelapse_options__free_unpacked
                     (Insta360__Messages__GetTimelapseOptions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__get_timelapse_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__get_timelapse_options_resp__init
                     (Insta360__Messages__GetTimelapseOptionsResp         *message)
{
  static const Insta360__Messages__GetTimelapseOptionsResp init_value = INSTA360__MESSAGES__GET_TIMELAPSE_OPTIONS_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__get_timelapse_options_resp__get_packed_size
                     (const Insta360__Messages__GetTimelapseOptionsResp *message)
{
  assert(message->base.descriptor == &insta360__messages__get_timelapse_options_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__get_timelapse_options_resp__pack
                     (const Insta360__Messages__GetTimelapseOptionsResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__get_timelapse_options_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__get_timelapse_options_resp__pack_to_buffer
                     (const Insta360__Messages__GetTimelapseOptionsResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__get_timelapse_options_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__GetTimelapseOptionsResp *
       insta360__messages__get_timelapse_options_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__GetTimelapseOptionsResp *)
     protobuf_c_message_unpack (&insta360__messages__get_timelapse_options_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__get_timelapse_options_resp__free_unpacked
                     (Insta360__Messages__GetTimelapseOptionsResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__get_timelapse_options_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__get_timelapse_options__field_descriptors[1] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetTimelapseOptions, mode),
    &insta360__messages__timelapse_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_timelapse_options__field_indices_by_name[] = {
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange insta360__messages__get_timelapse_options__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__get_timelapse_options__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetTimelapseOptions",
  "GetTimelapseOptions",
  "Insta360__Messages__GetTimelapseOptions",
  "insta360.messages",
  sizeof(Insta360__Messages__GetTimelapseOptions),
  1,
  insta360__messages__get_timelapse_options__field_descriptors,
  insta360__messages__get_timelapse_options__field_indices_by_name,
  1,  insta360__messages__get_timelapse_options__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_timelapse_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__get_timelapse_options_resp__field_descriptors[1] =
{
  {
    "timelapse_options",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetTimelapseOptionsResp, timelapse_options),
    &insta360__messages__timelapse_options__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_timelapse_options_resp__field_indices_by_name[] = {
  0,   /* field[0] = timelapse_options */
};
static const ProtobufCIntRange insta360__messages__get_timelapse_options_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__get_timelapse_options_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetTimelapseOptionsResp",
  "GetTimelapseOptionsResp",
  "Insta360__Messages__GetTimelapseOptionsResp",
  "insta360.messages",
  sizeof(Insta360__Messages__GetTimelapseOptionsResp),
  1,
  insta360__messages__get_timelapse_options_resp__field_descriptors,
  insta360__messages__get_timelapse_options_resp__field_indices_by_name,
  1,  insta360__messages__get_timelapse_options_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_timelapse_options_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
