/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: get_timelapse_options.proto */

#ifndef PROTOBUF_C_get_5ftimelapse_5foptions_2eproto__INCLUDED
#define PROTOBUF_C_get_5ftimelapse_5foptions_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "timelapse.pb-c.h"

typedef struct Insta360__Messages__GetTimelapseOptions Insta360__Messages__GetTimelapseOptions;
typedef struct Insta360__Messages__GetTimelapseOptionsResp Insta360__Messages__GetTimelapseOptionsResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__GetTimelapseOptions
{
  ProtobufCMessage base;
  Insta360__Messages__TimelapseMode mode;
};
#define INSTA360__MESSAGES__GET_TIMELAPSE_OPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_timelapse_options__descriptor) \
    , INSTA360__MESSAGES__TIMELAPSE_MODE__TIMELAPSE_MIXED }


struct  Insta360__Messages__GetTimelapseOptionsResp
{
  ProtobufCMessage base;
  Insta360__Messages__TimelapseOptions *timelapse_options;
};
#define INSTA360__MESSAGES__GET_TIMELAPSE_OPTIONS_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_timelapse_options_resp__descriptor) \
    , NULL }


/* Insta360__Messages__GetTimelapseOptions methods */
void   insta360__messages__get_timelapse_options__init
                     (Insta360__Messages__GetTimelapseOptions         *message);
size_t insta360__messages__get_timelapse_options__get_packed_size
                     (const Insta360__Messages__GetTimelapseOptions   *message);
size_t insta360__messages__get_timelapse_options__pack
                     (const Insta360__Messages__GetTimelapseOptions   *message,
                      uint8_t             *out);
size_t insta360__messages__get_timelapse_options__pack_to_buffer
                     (const Insta360__Messages__GetTimelapseOptions   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetTimelapseOptions *
       insta360__messages__get_timelapse_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_timelapse_options__free_unpacked
                     (Insta360__Messages__GetTimelapseOptions *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__GetTimelapseOptionsResp methods */
void   insta360__messages__get_timelapse_options_resp__init
                     (Insta360__Messages__GetTimelapseOptionsResp         *message);
size_t insta360__messages__get_timelapse_options_resp__get_packed_size
                     (const Insta360__Messages__GetTimelapseOptionsResp   *message);
size_t insta360__messages__get_timelapse_options_resp__pack
                     (const Insta360__Messages__GetTimelapseOptionsResp   *message,
                      uint8_t             *out);
size_t insta360__messages__get_timelapse_options_resp__pack_to_buffer
                     (const Insta360__Messages__GetTimelapseOptionsResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetTimelapseOptionsResp *
       insta360__messages__get_timelapse_options_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_timelapse_options_resp__free_unpacked
                     (Insta360__Messages__GetTimelapseOptionsResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__GetTimelapseOptions_Closure)
                 (const Insta360__Messages__GetTimelapseOptions *message,
                  void *closure_data);
typedef void (*Insta360__Messages__GetTimelapseOptionsResp_Closure)
                 (const Insta360__Messages__GetTimelapseOptionsResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__get_timelapse_options__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__get_timelapse_options_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_get_5ftimelapse_5foptions_2eproto__INCLUDED */
