/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: get_options.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "get_options.pb-c.h"
void   insta360__messages__get_options__init
                     (Insta360__Messages__GetOptions         *message)
{
  static const Insta360__Messages__GetOptions init_value = INSTA360__MESSAGES__GET_OPTIONS__INIT;
  *message = init_value;
}
size_t insta360__messages__get_options__get_packed_size
                     (const Insta360__Messages__GetOptions *message)
{
  assert(message->base.descriptor == &insta360__messages__get_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__get_options__pack
                     (const Insta360__Messages__GetOptions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__get_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__get_options__pack_to_buffer
                     (const Insta360__Messages__GetOptions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__get_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__GetOptions *
       insta360__messages__get_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__GetOptions *)
     protobuf_c_message_unpack (&insta360__messages__get_options__descriptor,
                                allocator, len, data);
}
void   insta360__messages__get_options__free_unpacked
                     (Insta360__Messages__GetOptions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__get_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__get_options_resp__init
                     (Insta360__Messages__GetOptionsResp         *message)
{
  static const Insta360__Messages__GetOptionsResp init_value = INSTA360__MESSAGES__GET_OPTIONS_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__get_options_resp__get_packed_size
                     (const Insta360__Messages__GetOptionsResp *message)
{
  assert(message->base.descriptor == &insta360__messages__get_options_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__get_options_resp__pack
                     (const Insta360__Messages__GetOptionsResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__get_options_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__get_options_resp__pack_to_buffer
                     (const Insta360__Messages__GetOptionsResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__get_options_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__GetOptionsResp *
       insta360__messages__get_options_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__GetOptionsResp *)
     protobuf_c_message_unpack (&insta360__messages__get_options_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__get_options_resp__free_unpacked
                     (Insta360__Messages__GetOptionsResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__get_options_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__get_options__field_descriptors[1] =
{
  {
    "option_types",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Insta360__Messages__GetOptions, n_option_types),
    offsetof(Insta360__Messages__GetOptions, option_types),
    &insta360__messages__option_type__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_options__field_indices_by_name[] = {
  0,   /* field[0] = option_types */
};
static const ProtobufCIntRange insta360__messages__get_options__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__get_options__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetOptions",
  "GetOptions",
  "Insta360__Messages__GetOptions",
  "insta360.messages",
  sizeof(Insta360__Messages__GetOptions),
  1,
  insta360__messages__get_options__field_descriptors,
  insta360__messages__get_options__field_indices_by_name,
  1,  insta360__messages__get_options__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__get_options_resp__field_descriptors[2] =
{
  {
    "option_types",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Insta360__Messages__GetOptionsResp, n_option_types),
    offsetof(Insta360__Messages__GetOptionsResp, option_types),
    &insta360__messages__option_type__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetOptionsResp, value),
    &insta360__messages__options__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_options_resp__field_indices_by_name[] = {
  0,   /* field[0] = option_types */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange insta360__messages__get_options_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__get_options_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetOptionsResp",
  "GetOptionsResp",
  "Insta360__Messages__GetOptionsResp",
  "insta360.messages",
  sizeof(Insta360__Messages__GetOptionsResp),
  2,
  insta360__messages__get_options_resp__field_descriptors,
  insta360__messages__get_options_resp__field_indices_by_name,
  1,  insta360__messages__get_options_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_options_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
