/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: get_file_extra.proto */

#ifndef PROTOBUF_C_get_5ffile_5fextra_2eproto__INCLUDED
#define PROTOBUF_C_get_5ffile_5fextra_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "media.pb-c.h"
#include "extra_info.pb-c.h"

typedef struct Insta360__Messages__GetFileExtra Insta360__Messages__GetFileExtra;
typedef struct Insta360__Messages__GetFileExtra__GyroOptions Insta360__Messages__GetFileExtra__GyroOptions;
typedef struct Insta360__Messages__GetFileExtra__GyroOptions__IndexRange Insta360__Messages__GetFileExtra__GyroOptions__IndexRange;
typedef struct Insta360__Messages__GetFileExtra__GyroOptions__TimeRange Insta360__Messages__GetFileExtra__GyroOptions__TimeRange;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__GetFileExtra__GyroOptions__IndexRange
{
  ProtobufCMessage base;
  int32_t start;
  int32_t count;
};
#define INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__INDEX_RANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_file_extra__gyro_options__index_range__descriptor) \
    , 0, 0 }


struct  Insta360__Messages__GetFileExtra__GyroOptions__TimeRange
{
  ProtobufCMessage base;
  int64_t start;
  int64_t duration;
};
#define INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__TIME_RANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_file_extra__gyro_options__time_range__descriptor) \
    , 0, 0 }


typedef enum {
  INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__RANGE__NOT_SET = 0,
  INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__RANGE_INDEX_RANGE = 1,
  INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__RANGE_TIME_RANGE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__RANGE__CASE)
} Insta360__Messages__GetFileExtra__GyroOptions__RangeCase;

struct  Insta360__Messages__GetFileExtra__GyroOptions
{
  ProtobufCMessage base;
  Insta360__Messages__GetFileExtra__GyroOptions__RangeCase range_case;
  union {
    Insta360__Messages__GetFileExtra__GyroOptions__IndexRange *index_range;
    Insta360__Messages__GetFileExtra__GyroOptions__TimeRange *time_range;
  };
};
#define INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_file_extra__gyro_options__descriptor) \
    , INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__RANGE__NOT_SET, {0} }


struct  Insta360__Messages__GetFileExtra
{
  ProtobufCMessage base;
  char *uri;
  uint32_t extra_type;
  Insta360__Messages__GetFileExtra__GyroOptions *gyro_options;
};
#define INSTA360__MESSAGES__GET_FILE_EXTRA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_file_extra__descriptor) \
    , (char *)protobuf_c_empty_string, 0, NULL }


/* Insta360__Messages__GetFileExtra__GyroOptions__IndexRange methods */
void   insta360__messages__get_file_extra__gyro_options__index_range__init
                     (Insta360__Messages__GetFileExtra__GyroOptions__IndexRange         *message);
/* Insta360__Messages__GetFileExtra__GyroOptions__TimeRange methods */
void   insta360__messages__get_file_extra__gyro_options__time_range__init
                     (Insta360__Messages__GetFileExtra__GyroOptions__TimeRange         *message);
/* Insta360__Messages__GetFileExtra__GyroOptions methods */
void   insta360__messages__get_file_extra__gyro_options__init
                     (Insta360__Messages__GetFileExtra__GyroOptions         *message);
/* Insta360__Messages__GetFileExtra methods */
void   insta360__messages__get_file_extra__init
                     (Insta360__Messages__GetFileExtra         *message);
size_t insta360__messages__get_file_extra__get_packed_size
                     (const Insta360__Messages__GetFileExtra   *message);
size_t insta360__messages__get_file_extra__pack
                     (const Insta360__Messages__GetFileExtra   *message,
                      uint8_t             *out);
size_t insta360__messages__get_file_extra__pack_to_buffer
                     (const Insta360__Messages__GetFileExtra   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetFileExtra *
       insta360__messages__get_file_extra__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_file_extra__free_unpacked
                     (Insta360__Messages__GetFileExtra *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__GetFileExtra__GyroOptions__IndexRange_Closure)
                 (const Insta360__Messages__GetFileExtra__GyroOptions__IndexRange *message,
                  void *closure_data);
typedef void (*Insta360__Messages__GetFileExtra__GyroOptions__TimeRange_Closure)
                 (const Insta360__Messages__GetFileExtra__GyroOptions__TimeRange *message,
                  void *closure_data);
typedef void (*Insta360__Messages__GetFileExtra__GyroOptions_Closure)
                 (const Insta360__Messages__GetFileExtra__GyroOptions *message,
                  void *closure_data);
typedef void (*Insta360__Messages__GetFileExtra_Closure)
                 (const Insta360__Messages__GetFileExtra *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__get_file_extra__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__get_file_extra__gyro_options__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__get_file_extra__gyro_options__index_range__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__get_file_extra__gyro_options__time_range__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_get_5ffile_5fextra_2eproto__INCLUDED */
