/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: get_options.proto */

#ifndef PROTOBUF_C_get_5foptions_2eproto__INCLUDED
#define PROTOBUF_C_get_5foptions_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "options.pb-c.h"

typedef struct Insta360__Messages__GetOptions Insta360__Messages__GetOptions;
typedef struct Insta360__Messages__GetOptionsResp Insta360__Messages__GetOptionsResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__GetOptions
{
  ProtobufCMessage base;
  size_t n_option_types;
  Insta360__Messages__OptionType *option_types;
};
#define INSTA360__MESSAGES__GET_OPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_options__descriptor) \
    , 0,NULL }


struct  Insta360__Messages__GetOptionsResp
{
  ProtobufCMessage base;
  size_t n_option_types;
  Insta360__Messages__OptionType *option_types;
  Insta360__Messages__Options *value;
};
#define INSTA360__MESSAGES__GET_OPTIONS_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_options_resp__descriptor) \
    , 0,NULL, NULL }


/* Insta360__Messages__GetOptions methods */
void   insta360__messages__get_options__init
                     (Insta360__Messages__GetOptions         *message);
size_t insta360__messages__get_options__get_packed_size
                     (const Insta360__Messages__GetOptions   *message);
size_t insta360__messages__get_options__pack
                     (const Insta360__Messages__GetOptions   *message,
                      uint8_t             *out);
size_t insta360__messages__get_options__pack_to_buffer
                     (const Insta360__Messages__GetOptions   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetOptions *
       insta360__messages__get_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_options__free_unpacked
                     (Insta360__Messages__GetOptions *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__GetOptionsResp methods */
void   insta360__messages__get_options_resp__init
                     (Insta360__Messages__GetOptionsResp         *message);
size_t insta360__messages__get_options_resp__get_packed_size
                     (const Insta360__Messages__GetOptionsResp   *message);
size_t insta360__messages__get_options_resp__pack
                     (const Insta360__Messages__GetOptionsResp   *message,
                      uint8_t             *out);
size_t insta360__messages__get_options_resp__pack_to_buffer
                     (const Insta360__Messages__GetOptionsResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetOptionsResp *
       insta360__messages__get_options_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_options_resp__free_unpacked
                     (Insta360__Messages__GetOptionsResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__GetOptions_Closure)
                 (const Insta360__Messages__GetOptions *message,
                  void *closure_data);
typedef void (*Insta360__Messages__GetOptionsResp_Closure)
                 (const Insta360__Messages__GetOptionsResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__get_options__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__get_options_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_get_5foptions_2eproto__INCLUDED */
