/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: get_gyro.proto */

#ifndef PROTOBUF_C_get_5fgyro_2eproto__INCLUDED
#define PROTOBUF_C_get_5fgyro_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__GetGyro Insta360__Messages__GetGyro;
typedef struct Insta360__Messages__GetGyroResp Insta360__Messages__GetGyroResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__GetGyro
{
  ProtobufCMessage base;
  uint32_t count;
};
#define INSTA360__MESSAGES__GET_GYRO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_gyro__descriptor) \
    , 0 }


struct  Insta360__Messages__GetGyroResp
{
  ProtobufCMessage base;
  ProtobufCBinaryData gyroes;
};
#define INSTA360__MESSAGES__GET_GYRO_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_gyro_resp__descriptor) \
    , {0,NULL} }


/* Insta360__Messages__GetGyro methods */
void   insta360__messages__get_gyro__init
                     (Insta360__Messages__GetGyro         *message);
size_t insta360__messages__get_gyro__get_packed_size
                     (const Insta360__Messages__GetGyro   *message);
size_t insta360__messages__get_gyro__pack
                     (const Insta360__Messages__GetGyro   *message,
                      uint8_t             *out);
size_t insta360__messages__get_gyro__pack_to_buffer
                     (const Insta360__Messages__GetGyro   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetGyro *
       insta360__messages__get_gyro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_gyro__free_unpacked
                     (Insta360__Messages__GetGyro *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__GetGyroResp methods */
void   insta360__messages__get_gyro_resp__init
                     (Insta360__Messages__GetGyroResp         *message);
size_t insta360__messages__get_gyro_resp__get_packed_size
                     (const Insta360__Messages__GetGyroResp   *message);
size_t insta360__messages__get_gyro_resp__pack
                     (const Insta360__Messages__GetGyroResp   *message,
                      uint8_t             *out);
size_t insta360__messages__get_gyro_resp__pack_to_buffer
                     (const Insta360__Messages__GetGyroResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetGyroResp *
       insta360__messages__get_gyro_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_gyro_resp__free_unpacked
                     (Insta360__Messages__GetGyroResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__GetGyro_Closure)
                 (const Insta360__Messages__GetGyro *message,
                  void *closure_data);
typedef void (*Insta360__Messages__GetGyroResp_Closure)
                 (const Insta360__Messages__GetGyroResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__get_gyro__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__get_gyro_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_get_5fgyro_2eproto__INCLUDED */
