/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: get_mini_thumbnail.proto */

#ifndef PROTOBUF_C_get_5fmini_5fthumbnail_2eproto__INCLUDED
#define PROTOBUF_C_get_5fmini_5fthumbnail_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__GetMiniThumbnail Insta360__Messages__GetMiniThumbnail;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__GetMiniThumbnail
{
  ProtobufCMessage base;
  char *uri;
};
#define INSTA360__MESSAGES__GET_MINI_THUMBNAIL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_mini_thumbnail__descriptor) \
    , (char *)protobuf_c_empty_string }


/* Insta360__Messages__GetMiniThumbnail methods */
void   insta360__messages__get_mini_thumbnail__init
                     (Insta360__Messages__GetMiniThumbnail         *message);
size_t insta360__messages__get_mini_thumbnail__get_packed_size
                     (const Insta360__Messages__GetMiniThumbnail   *message);
size_t insta360__messages__get_mini_thumbnail__pack
                     (const Insta360__Messages__GetMiniThumbnail   *message,
                      uint8_t             *out);
size_t insta360__messages__get_mini_thumbnail__pack_to_buffer
                     (const Insta360__Messages__GetMiniThumbnail   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetMiniThumbnail *
       insta360__messages__get_mini_thumbnail__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_mini_thumbnail__free_unpacked
                     (Insta360__Messages__GetMiniThumbnail *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__GetMiniThumbnail_Closure)
                 (const Insta360__Messages__GetMiniThumbnail *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__get_mini_thumbnail__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_get_5fmini_5fthumbnail_2eproto__INCLUDED */
