/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: get_file_extra.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "get_file_extra.pb-c.h"
void   insta360__messages__get_file_extra__gyro_options__index_range__init
                     (Insta360__Messages__GetFileExtra__GyroOptions__IndexRange         *message)
{
  static const Insta360__Messages__GetFileExtra__GyroOptions__IndexRange init_value = INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__INDEX_RANGE__INIT;
  *message = init_value;
}
void   insta360__messages__get_file_extra__gyro_options__time_range__init
                     (Insta360__Messages__GetFileExtra__GyroOptions__TimeRange         *message)
{
  static const Insta360__Messages__GetFileExtra__GyroOptions__TimeRange init_value = INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__TIME_RANGE__INIT;
  *message = init_value;
}
void   insta360__messages__get_file_extra__gyro_options__init
                     (Insta360__Messages__GetFileExtra__GyroOptions         *message)
{
  static const Insta360__Messages__GetFileExtra__GyroOptions init_value = INSTA360__MESSAGES__GET_FILE_EXTRA__GYRO_OPTIONS__INIT;
  *message = init_value;
}
void   insta360__messages__get_file_extra__init
                     (Insta360__Messages__GetFileExtra         *message)
{
  static const Insta360__Messages__GetFileExtra init_value = INSTA360__MESSAGES__GET_FILE_EXTRA__INIT;
  *message = init_value;
}
size_t insta360__messages__get_file_extra__get_packed_size
                     (const Insta360__Messages__GetFileExtra *message)
{
  assert(message->base.descriptor == &insta360__messages__get_file_extra__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__get_file_extra__pack
                     (const Insta360__Messages__GetFileExtra *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__get_file_extra__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__get_file_extra__pack_to_buffer
                     (const Insta360__Messages__GetFileExtra *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__get_file_extra__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__GetFileExtra *
       insta360__messages__get_file_extra__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__GetFileExtra *)
     protobuf_c_message_unpack (&insta360__messages__get_file_extra__descriptor,
                                allocator, len, data);
}
void   insta360__messages__get_file_extra__free_unpacked
                     (Insta360__Messages__GetFileExtra *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__get_file_extra__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__get_file_extra__gyro_options__index_range__field_descriptors[2] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetFileExtra__GyroOptions__IndexRange, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetFileExtra__GyroOptions__IndexRange, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_file_extra__gyro_options__index_range__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = start */
};
static const ProtobufCIntRange insta360__messages__get_file_extra__gyro_options__index_range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__get_file_extra__gyro_options__index_range__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetFileExtra.GyroOptions.IndexRange",
  "IndexRange",
  "Insta360__Messages__GetFileExtra__GyroOptions__IndexRange",
  "insta360.messages",
  sizeof(Insta360__Messages__GetFileExtra__GyroOptions__IndexRange),
  2,
  insta360__messages__get_file_extra__gyro_options__index_range__field_descriptors,
  insta360__messages__get_file_extra__gyro_options__index_range__field_indices_by_name,
  1,  insta360__messages__get_file_extra__gyro_options__index_range__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_file_extra__gyro_options__index_range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__get_file_extra__gyro_options__time_range__field_descriptors[2] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetFileExtra__GyroOptions__TimeRange, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetFileExtra__GyroOptions__TimeRange, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_file_extra__gyro_options__time_range__field_indices_by_name[] = {
  1,   /* field[1] = duration */
  0,   /* field[0] = start */
};
static const ProtobufCIntRange insta360__messages__get_file_extra__gyro_options__time_range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__get_file_extra__gyro_options__time_range__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetFileExtra.GyroOptions.TimeRange",
  "TimeRange",
  "Insta360__Messages__GetFileExtra__GyroOptions__TimeRange",
  "insta360.messages",
  sizeof(Insta360__Messages__GetFileExtra__GyroOptions__TimeRange),
  2,
  insta360__messages__get_file_extra__gyro_options__time_range__field_descriptors,
  insta360__messages__get_file_extra__gyro_options__time_range__field_indices_by_name,
  1,  insta360__messages__get_file_extra__gyro_options__time_range__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_file_extra__gyro_options__time_range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__get_file_extra__gyro_options__field_descriptors[2] =
{
  {
    "index_range",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Insta360__Messages__GetFileExtra__GyroOptions, range_case),
    offsetof(Insta360__Messages__GetFileExtra__GyroOptions, index_range),
    &insta360__messages__get_file_extra__gyro_options__index_range__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_range",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Insta360__Messages__GetFileExtra__GyroOptions, range_case),
    offsetof(Insta360__Messages__GetFileExtra__GyroOptions, time_range),
    &insta360__messages__get_file_extra__gyro_options__time_range__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_file_extra__gyro_options__field_indices_by_name[] = {
  0,   /* field[0] = index_range */
  1,   /* field[1] = time_range */
};
static const ProtobufCIntRange insta360__messages__get_file_extra__gyro_options__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__get_file_extra__gyro_options__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetFileExtra.GyroOptions",
  "GyroOptions",
  "Insta360__Messages__GetFileExtra__GyroOptions",
  "insta360.messages",
  sizeof(Insta360__Messages__GetFileExtra__GyroOptions),
  2,
  insta360__messages__get_file_extra__gyro_options__field_descriptors,
  insta360__messages__get_file_extra__gyro_options__field_indices_by_name,
  1,  insta360__messages__get_file_extra__gyro_options__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_file_extra__gyro_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__get_file_extra__field_descriptors[3] =
{
  {
    "uri",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetFileExtra, uri),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extra_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetFileExtra, extra_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_options",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GetFileExtra, gyro_options),
    &insta360__messages__get_file_extra__gyro_options__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__get_file_extra__field_indices_by_name[] = {
  1,   /* field[1] = extra_type */
  2,   /* field[2] = gyro_options */
  0,   /* field[0] = uri */
};
static const ProtobufCIntRange insta360__messages__get_file_extra__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor insta360__messages__get_file_extra__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GetFileExtra",
  "GetFileExtra",
  "Insta360__Messages__GetFileExtra",
  "insta360.messages",
  sizeof(Insta360__Messages__GetFileExtra),
  3,
  insta360__messages__get_file_extra__field_descriptors,
  insta360__messages__get_file_extra__field_indices_by_name,
  1,  insta360__messages__get_file_extra__number_ranges,
  (ProtobufCMessageInit) insta360__messages__get_file_extra__init,
  NULL,NULL,NULL    /* reserved[123] */
};
