/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: get_sync_capture_mode.proto */

#ifndef PROTOBUF_C_get_5fsync_5fcapture_5fmode_2eproto__INCLUDED
#define PROTOBUF_C_get_5fsync_5fcapture_5fmode_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "sync_capture_mode.pb-c.h"

typedef struct Insta360__Messages__GetSyncCaptureMode Insta360__Messages__GetSyncCaptureMode;
typedef struct Insta360__Messages__GetSyncCaptureModeResp Insta360__Messages__GetSyncCaptureModeResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__GetSyncCaptureMode
{
  ProtobufCMessage base;
};
#define INSTA360__MESSAGES__GET_SYNC_CAPTURE_MODE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_sync_capture_mode__descriptor) \
     }


struct  Insta360__Messages__GetSyncCaptureModeResp
{
  ProtobufCMessage base;
  Insta360__Messages__SyncCaptureMode capture_mode;
};
#define INSTA360__MESSAGES__GET_SYNC_CAPTURE_MODE_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__get_sync_capture_mode_resp__descriptor) \
    , INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_UNKNOWN }


/* Insta360__Messages__GetSyncCaptureMode methods */
void   insta360__messages__get_sync_capture_mode__init
                     (Insta360__Messages__GetSyncCaptureMode         *message);
size_t insta360__messages__get_sync_capture_mode__get_packed_size
                     (const Insta360__Messages__GetSyncCaptureMode   *message);
size_t insta360__messages__get_sync_capture_mode__pack
                     (const Insta360__Messages__GetSyncCaptureMode   *message,
                      uint8_t             *out);
size_t insta360__messages__get_sync_capture_mode__pack_to_buffer
                     (const Insta360__Messages__GetSyncCaptureMode   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetSyncCaptureMode *
       insta360__messages__get_sync_capture_mode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_sync_capture_mode__free_unpacked
                     (Insta360__Messages__GetSyncCaptureMode *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__GetSyncCaptureModeResp methods */
void   insta360__messages__get_sync_capture_mode_resp__init
                     (Insta360__Messages__GetSyncCaptureModeResp         *message);
size_t insta360__messages__get_sync_capture_mode_resp__get_packed_size
                     (const Insta360__Messages__GetSyncCaptureModeResp   *message);
size_t insta360__messages__get_sync_capture_mode_resp__pack
                     (const Insta360__Messages__GetSyncCaptureModeResp   *message,
                      uint8_t             *out);
size_t insta360__messages__get_sync_capture_mode_resp__pack_to_buffer
                     (const Insta360__Messages__GetSyncCaptureModeResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GetSyncCaptureModeResp *
       insta360__messages__get_sync_capture_mode_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__get_sync_capture_mode_resp__free_unpacked
                     (Insta360__Messages__GetSyncCaptureModeResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__GetSyncCaptureMode_Closure)
                 (const Insta360__Messages__GetSyncCaptureMode *message,
                  void *closure_data);
typedef void (*Insta360__Messages__GetSyncCaptureModeResp_Closure)
                 (const Insta360__Messages__GetSyncCaptureModeResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__get_sync_capture_mode__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__get_sync_capture_mode_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_get_5fsync_5fcapture_5fmode_2eproto__INCLUDED */
