/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: key_pressed.proto */

#ifndef PROTOBUF_C_key_5fpressed_2eproto__INCLUDED
#define PROTOBUF_C_key_5fpressed_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__NotificatoinKeyPressed Insta360__Messages__NotificatoinKeyPressed;


/* --- enums --- */

typedef enum _Insta360__Messages__NotificatoinKeyPressed__KeyId {
  INSTA360__MESSAGES__NOTIFICATOIN_KEY_PRESSED__KEY_ID__F0_SHORT_PRESS = 0,
  INSTA360__MESSAGES__NOTIFICATOIN_KEY_PRESSED__KEY_ID__F0_DOUBLE_PRESS = 1,
  INSTA360__MESSAGES__NOTIFICATOIN_KEY_PRESSED__KEY_ID__F0_TRIPLE_PRESS = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__NOTIFICATOIN_KEY_PRESSED__KEY_ID)
} Insta360__Messages__NotificatoinKeyPressed__KeyId;

/* --- messages --- */

struct  Insta360__Messages__NotificatoinKeyPressed
{
  ProtobufCMessage base;
  Insta360__Messages__NotificatoinKeyPressed__KeyId key_id;
};
#define INSTA360__MESSAGES__NOTIFICATOIN_KEY_PRESSED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__notificatoin_key_pressed__descriptor) \
    , INSTA360__MESSAGES__NOTIFICATOIN_KEY_PRESSED__KEY_ID__F0_SHORT_PRESS }


/* Insta360__Messages__NotificatoinKeyPressed methods */
void   insta360__messages__notificatoin_key_pressed__init
                     (Insta360__Messages__NotificatoinKeyPressed         *message);
size_t insta360__messages__notificatoin_key_pressed__get_packed_size
                     (const Insta360__Messages__NotificatoinKeyPressed   *message);
size_t insta360__messages__notificatoin_key_pressed__pack
                     (const Insta360__Messages__NotificatoinKeyPressed   *message,
                      uint8_t             *out);
size_t insta360__messages__notificatoin_key_pressed__pack_to_buffer
                     (const Insta360__Messages__NotificatoinKeyPressed   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__NotificatoinKeyPressed *
       insta360__messages__notificatoin_key_pressed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__notificatoin_key_pressed__free_unpacked
                     (Insta360__Messages__NotificatoinKeyPressed *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__NotificatoinKeyPressed_Closure)
                 (const Insta360__Messages__NotificatoinKeyPressed *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__notificatoin_key_pressed__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__notificatoin_key_pressed__key_id__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_key_5fpressed_2eproto__INCLUDED */
