/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: media.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "media.pb-c.h"
void   insta360__messages__gps__init
                     (Insta360__Messages__GPS         *message)
{
  static const Insta360__Messages__GPS init_value = INSTA360__MESSAGES__GPS__INIT;
  *message = init_value;
}
size_t insta360__messages__gps__get_packed_size
                     (const Insta360__Messages__GPS *message)
{
  assert(message->base.descriptor == &insta360__messages__gps__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__gps__pack
                     (const Insta360__Messages__GPS *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__gps__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__gps__pack_to_buffer
                     (const Insta360__Messages__GPS *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__gps__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__GPS *
       insta360__messages__gps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__GPS *)
     protobuf_c_message_unpack (&insta360__messages__gps__descriptor,
                                allocator, len, data);
}
void   insta360__messages__gps__free_unpacked
                     (Insta360__Messages__GPS *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__gps__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__gyro__init
                     (Insta360__Messages__Gyro         *message)
{
  static const Insta360__Messages__Gyro init_value = INSTA360__MESSAGES__GYRO__INIT;
  *message = init_value;
}
size_t insta360__messages__gyro__get_packed_size
                     (const Insta360__Messages__Gyro *message)
{
  assert(message->base.descriptor == &insta360__messages__gyro__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__gyro__pack
                     (const Insta360__Messages__Gyro *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__gyro__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__gyro__pack_to_buffer
                     (const Insta360__Messages__Gyro *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__gyro__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__Gyro *
       insta360__messages__gyro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__Gyro *)
     protobuf_c_message_unpack (&insta360__messages__gyro__descriptor,
                                allocator, len, data);
}
void   insta360__messages__gyro__free_unpacked
                     (Insta360__Messages__Gyro *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__gyro__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__orientation__init
                     (Insta360__Messages__Orientation         *message)
{
  static const Insta360__Messages__Orientation init_value = INSTA360__MESSAGES__ORIENTATION__INIT;
  *message = init_value;
}
size_t insta360__messages__orientation__get_packed_size
                     (const Insta360__Messages__Orientation *message)
{
  assert(message->base.descriptor == &insta360__messages__orientation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__orientation__pack
                     (const Insta360__Messages__Orientation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__orientation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__orientation__pack_to_buffer
                     (const Insta360__Messages__Orientation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__orientation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__Orientation *
       insta360__messages__orientation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__Orientation *)
     protobuf_c_message_unpack (&insta360__messages__orientation__descriptor,
                                allocator, len, data);
}
void   insta360__messages__orientation__free_unpacked
                     (Insta360__Messages__Orientation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__orientation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__gps__field_descriptors[3] =
{
  {
    "longitude",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GPS, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GPS, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__GPS, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__gps__field_indices_by_name[] = {
  2,   /* field[2] = altitude */
  1,   /* field[1] = latitude */
  0,   /* field[0] = longitude */
};
static const ProtobufCIntRange insta360__messages__gps__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor insta360__messages__gps__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.GPS",
  "GPS",
  "Insta360__Messages__GPS",
  "insta360.messages",
  sizeof(Insta360__Messages__GPS),
  3,
  insta360__messages__gps__field_descriptors,
  insta360__messages__gps__field_indices_by_name,
  1,  insta360__messages__gps__number_ranges,
  (ProtobufCMessageInit) insta360__messages__gps__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__gyro__field_descriptors[6] =
{
  {
    "ax",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Gyro, ax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ay",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Gyro, ay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "az",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Gyro, az),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gx",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Gyro, gx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gy",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Gyro, gy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gz",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Gyro, gz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__gyro__field_indices_by_name[] = {
  0,   /* field[0] = ax */
  1,   /* field[1] = ay */
  2,   /* field[2] = az */
  3,   /* field[3] = gx */
  4,   /* field[4] = gy */
  5,   /* field[5] = gz */
};
static const ProtobufCIntRange insta360__messages__gyro__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor insta360__messages__gyro__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.Gyro",
  "Gyro",
  "Insta360__Messages__Gyro",
  "insta360.messages",
  sizeof(Insta360__Messages__Gyro),
  6,
  insta360__messages__gyro__field_descriptors,
  insta360__messages__gyro__field_indices_by_name,
  1,  insta360__messages__gyro__number_ranges,
  (ProtobufCMessageInit) insta360__messages__gyro__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__orientation__field_descriptors[4] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Orientation, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Orientation, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Orientation, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__Orientation, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__orientation__field_indices_by_name[] = {
  3,   /* field[3] = w */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange insta360__messages__orientation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor insta360__messages__orientation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.Orientation",
  "Orientation",
  "Insta360__Messages__Orientation",
  "insta360.messages",
  sizeof(Insta360__Messages__Orientation),
  4,
  insta360__messages__orientation__field_descriptors,
  insta360__messages__orientation__field_indices_by_name,
  1,  insta360__messages__orientation__number_ranges,
  (ProtobufCMessageInit) insta360__messages__orientation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue insta360__messages__aacbstype__enum_values_by_number[2] =
{
  { "RAW", "INSTA360__MESSAGES__AACBSTYPE__RAW", 0 },
  { "ADTS", "INSTA360__MESSAGES__AACBSTYPE__ADTS", 1 },
};
static const ProtobufCIntRange insta360__messages__aacbstype__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex insta360__messages__aacbstype__enum_values_by_name[2] =
{
  { "ADTS", 1 },
  { "RAW", 0 },
};
const ProtobufCEnumDescriptor insta360__messages__aacbstype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.AACBSType",
  "AACBSType",
  "Insta360__Messages__AACBSType",
  "insta360.messages",
  2,
  insta360__messages__aacbstype__enum_values_by_number,
  2,
  insta360__messages__aacbstype__enum_values_by_name,
  1,
  insta360__messages__aacbstype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue insta360__messages__media_type__enum_values_by_number[6] =
{
  { "VIDEO", "INSTA360__MESSAGES__MEDIA_TYPE__VIDEO", 0 },
  { "PHOTO", "INSTA360__MESSAGES__MEDIA_TYPE__PHOTO", 1 },
  { "VIDEO_AND_PHOTO", "INSTA360__MESSAGES__MEDIA_TYPE__VIDEO_AND_PHOTO", 2 },
  { "DNG", "INSTA360__MESSAGES__MEDIA_TYPE__DNG", 3 },
  { "MP4", "INSTA360__MESSAGES__MEDIA_TYPE__MP4", 4 },
  { "JPG", "INSTA360__MESSAGES__MEDIA_TYPE__JPG", 5 },
};
static const ProtobufCIntRange insta360__messages__media_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex insta360__messages__media_type__enum_values_by_name[6] =
{
  { "DNG", 3 },
  { "JPG", 5 },
  { "MP4", 4 },
  { "PHOTO", 1 },
  { "VIDEO", 0 },
  { "VIDEO_AND_PHOTO", 2 },
};
const ProtobufCEnumDescriptor insta360__messages__media_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.MediaType",
  "MediaType",
  "Insta360__Messages__MediaType",
  "insta360.messages",
  6,
  insta360__messages__media_type__enum_values_by_number,
  6,
  insta360__messages__media_type__enum_values_by_name,
  1,
  insta360__messages__media_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
