/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: media.proto */

#ifndef PROTOBUF_C_media_2eproto__INCLUDED
#define PROTOBUF_C_media_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__GPS Insta360__Messages__GPS;
typedef struct Insta360__Messages__Gyro Insta360__Messages__Gyro;
typedef struct Insta360__Messages__Orientation Insta360__Messages__Orientation;


/* --- enums --- */

typedef enum _Insta360__Messages__AACBSType {
  INSTA360__MESSAGES__AACBSTYPE__RAW = 0,
  INSTA360__MESSAGES__AACBSTYPE__ADTS = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__AACBSTYPE)
} Insta360__Messages__AACBSType;
typedef enum _Insta360__Messages__MediaType {
  INSTA360__MESSAGES__MEDIA_TYPE__VIDEO = 0,
  INSTA360__MESSAGES__MEDIA_TYPE__PHOTO = 1,
  INSTA360__MESSAGES__MEDIA_TYPE__VIDEO_AND_PHOTO = 2,
  INSTA360__MESSAGES__MEDIA_TYPE__DNG = 3,
  INSTA360__MESSAGES__MEDIA_TYPE__MP4 = 4,
  INSTA360__MESSAGES__MEDIA_TYPE__JPG = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__MEDIA_TYPE)
} Insta360__Messages__MediaType;

/* --- messages --- */

struct  Insta360__Messages__GPS
{
  ProtobufCMessage base;
  double longitude;
  double latitude;
  double altitude;
};
#define INSTA360__MESSAGES__GPS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__gps__descriptor) \
    , 0, 0, 0 }


struct  Insta360__Messages__Gyro
{
  ProtobufCMessage base;
  double ax;
  double ay;
  double az;
  double gx;
  double gy;
  double gz;
};
#define INSTA360__MESSAGES__GYRO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__gyro__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  Insta360__Messages__Orientation
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
  int32_t z;
  int32_t w;
};
#define INSTA360__MESSAGES__ORIENTATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__orientation__descriptor) \
    , 0, 0, 0, 0 }


/* Insta360__Messages__GPS methods */
void   insta360__messages__gps__init
                     (Insta360__Messages__GPS         *message);
size_t insta360__messages__gps__get_packed_size
                     (const Insta360__Messages__GPS   *message);
size_t insta360__messages__gps__pack
                     (const Insta360__Messages__GPS   *message,
                      uint8_t             *out);
size_t insta360__messages__gps__pack_to_buffer
                     (const Insta360__Messages__GPS   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__GPS *
       insta360__messages__gps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__gps__free_unpacked
                     (Insta360__Messages__GPS *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__Gyro methods */
void   insta360__messages__gyro__init
                     (Insta360__Messages__Gyro         *message);
size_t insta360__messages__gyro__get_packed_size
                     (const Insta360__Messages__Gyro   *message);
size_t insta360__messages__gyro__pack
                     (const Insta360__Messages__Gyro   *message,
                      uint8_t             *out);
size_t insta360__messages__gyro__pack_to_buffer
                     (const Insta360__Messages__Gyro   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__Gyro *
       insta360__messages__gyro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__gyro__free_unpacked
                     (Insta360__Messages__Gyro *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__Orientation methods */
void   insta360__messages__orientation__init
                     (Insta360__Messages__Orientation         *message);
size_t insta360__messages__orientation__get_packed_size
                     (const Insta360__Messages__Orientation   *message);
size_t insta360__messages__orientation__pack
                     (const Insta360__Messages__Orientation   *message,
                      uint8_t             *out);
size_t insta360__messages__orientation__pack_to_buffer
                     (const Insta360__Messages__Orientation   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__Orientation *
       insta360__messages__orientation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__orientation__free_unpacked
                     (Insta360__Messages__Orientation *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__GPS_Closure)
                 (const Insta360__Messages__GPS *message,
                  void *closure_data);
typedef void (*Insta360__Messages__Gyro_Closure)
                 (const Insta360__Messages__Gyro *message,
                  void *closure_data);
typedef void (*Insta360__Messages__Orientation_Closure)
                 (const Insta360__Messages__Orientation *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    insta360__messages__aacbstype__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__media_type__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__gps__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__gyro__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__orientation__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_media_2eproto__INCLUDED */
