/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: photo.proto */

#ifndef PROTOBUF_C_photo_2eproto__INCLUDED
#define PROTOBUF_C_photo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__Photo Insta360__Messages__Photo;


/* --- enums --- */

typedef enum _Insta360__Messages__PhotoSize {
  INSTA360__MESSAGES__PHOTO_SIZE__Size_6912_3456 = 0,
  INSTA360__MESSAGES__PHOTO_SIZE__Size_6272_3136 = 1,
  INSTA360__MESSAGES__PHOTO_SIZE__Size_6080_3040 = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__PHOTO_SIZE)
} Insta360__Messages__PhotoSize;
typedef enum _Insta360__Messages__PhotoSubMode {
  INSTA360__MESSAGES__PHOTO_SUB_MODE__PHOTO_SINGLE = 0,
  INSTA360__MESSAGES__PHOTO_SUB_MODE__PHOTO_HDR = 1,
  INSTA360__MESSAGES__PHOTO_SUB_MODE__PHOTO_INTERVAL = 2,
  INSTA360__MESSAGES__PHOTO_SUB_MODE__PHOTO_BURST = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__PHOTO_SUB_MODE)
} Insta360__Messages__PhotoSubMode;

/* --- messages --- */

struct  Insta360__Messages__Photo
{
  ProtobufCMessage base;
  char *uri;
  uint64_t file_size;
  ProtobufCBinaryData s_thumbnail;
};
#define INSTA360__MESSAGES__PHOTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__photo__descriptor) \
    , (char *)protobuf_c_empty_string, 0, {0,NULL} }


/* Insta360__Messages__Photo methods */
void   insta360__messages__photo__init
                     (Insta360__Messages__Photo         *message);
size_t insta360__messages__photo__get_packed_size
                     (const Insta360__Messages__Photo   *message);
size_t insta360__messages__photo__pack
                     (const Insta360__Messages__Photo   *message,
                      uint8_t             *out);
size_t insta360__messages__photo__pack_to_buffer
                     (const Insta360__Messages__Photo   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__Photo *
       insta360__messages__photo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__photo__free_unpacked
                     (Insta360__Messages__Photo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__Photo_Closure)
                 (const Insta360__Messages__Photo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    insta360__messages__photo_size__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__photo_sub_mode__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__photo__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_photo_2eproto__INCLUDED */
