/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sd_card_speed.proto */

#ifndef PROTOBUF_C_sd_5fcard_5fspeed_2eproto__INCLUDED
#define PROTOBUF_C_sd_5fcard_5fspeed_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__TestSDCardSpeed Insta360__Messages__TestSDCardSpeed;
typedef struct Insta360__Messages__TestSDCardSpeedResp Insta360__Messages__TestSDCardSpeedResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__TestSDCardSpeed
{
  ProtobufCMessage base;
  uint32_t block_size;
  uint32_t duration;
  uint32_t times;
};
#define INSTA360__MESSAGES__TEST_SDCARD_SPEED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__test_sdcard_speed__descriptor) \
    , 0, 0, 0 }


struct  Insta360__Messages__TestSDCardSpeedResp
{
  ProtobufCMessage base;
  size_t n_write_speeds;
  double *write_speeds;
};
#define INSTA360__MESSAGES__TEST_SDCARD_SPEED_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__test_sdcard_speed_resp__descriptor) \
    , 0,NULL }


/* Insta360__Messages__TestSDCardSpeed methods */
void   insta360__messages__test_sdcard_speed__init
                     (Insta360__Messages__TestSDCardSpeed         *message);
size_t insta360__messages__test_sdcard_speed__get_packed_size
                     (const Insta360__Messages__TestSDCardSpeed   *message);
size_t insta360__messages__test_sdcard_speed__pack
                     (const Insta360__Messages__TestSDCardSpeed   *message,
                      uint8_t             *out);
size_t insta360__messages__test_sdcard_speed__pack_to_buffer
                     (const Insta360__Messages__TestSDCardSpeed   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__TestSDCardSpeed *
       insta360__messages__test_sdcard_speed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__test_sdcard_speed__free_unpacked
                     (Insta360__Messages__TestSDCardSpeed *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__TestSDCardSpeedResp methods */
void   insta360__messages__test_sdcard_speed_resp__init
                     (Insta360__Messages__TestSDCardSpeedResp         *message);
size_t insta360__messages__test_sdcard_speed_resp__get_packed_size
                     (const Insta360__Messages__TestSDCardSpeedResp   *message);
size_t insta360__messages__test_sdcard_speed_resp__pack
                     (const Insta360__Messages__TestSDCardSpeedResp   *message,
                      uint8_t             *out);
size_t insta360__messages__test_sdcard_speed_resp__pack_to_buffer
                     (const Insta360__Messages__TestSDCardSpeedResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__TestSDCardSpeedResp *
       insta360__messages__test_sdcard_speed_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__test_sdcard_speed_resp__free_unpacked
                     (Insta360__Messages__TestSDCardSpeedResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__TestSDCardSpeed_Closure)
                 (const Insta360__Messages__TestSDCardSpeed *message,
                  void *closure_data);
typedef void (*Insta360__Messages__TestSDCardSpeedResp_Closure)
                 (const Insta360__Messages__TestSDCardSpeedResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__test_sdcard_speed__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__test_sdcard_speed_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sd_5fcard_5fspeed_2eproto__INCLUDED */
