/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: set_timelapse_options.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "set_timelapse_options.pb-c.h"
void   insta360__messages__set_timelapse_options__init
                     (Insta360__Messages__SetTimelapseOptions         *message)
{
  static const Insta360__Messages__SetTimelapseOptions init_value = INSTA360__MESSAGES__SET_TIMELAPSE_OPTIONS__INIT;
  *message = init_value;
}
size_t insta360__messages__set_timelapse_options__get_packed_size
                     (const Insta360__Messages__SetTimelapseOptions *message)
{
  assert(message->base.descriptor == &insta360__messages__set_timelapse_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__set_timelapse_options__pack
                     (const Insta360__Messages__SetTimelapseOptions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__set_timelapse_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__set_timelapse_options__pack_to_buffer
                     (const Insta360__Messages__SetTimelapseOptions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__set_timelapse_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__SetTimelapseOptions *
       insta360__messages__set_timelapse_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__SetTimelapseOptions *)
     protobuf_c_message_unpack (&insta360__messages__set_timelapse_options__descriptor,
                                allocator, len, data);
}
void   insta360__messages__set_timelapse_options__free_unpacked
                     (Insta360__Messages__SetTimelapseOptions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__set_timelapse_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__set_timelapse_options_resp__init
                     (Insta360__Messages__SetTimelapseOptionsResp         *message)
{
  static const Insta360__Messages__SetTimelapseOptionsResp init_value = INSTA360__MESSAGES__SET_TIMELAPSE_OPTIONS_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__set_timelapse_options_resp__get_packed_size
                     (const Insta360__Messages__SetTimelapseOptionsResp *message)
{
  assert(message->base.descriptor == &insta360__messages__set_timelapse_options_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__set_timelapse_options_resp__pack
                     (const Insta360__Messages__SetTimelapseOptionsResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__set_timelapse_options_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__set_timelapse_options_resp__pack_to_buffer
                     (const Insta360__Messages__SetTimelapseOptionsResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__set_timelapse_options_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__SetTimelapseOptionsResp *
       insta360__messages__set_timelapse_options_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__SetTimelapseOptionsResp *)
     protobuf_c_message_unpack (&insta360__messages__set_timelapse_options_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__set_timelapse_options_resp__free_unpacked
                     (Insta360__Messages__SetTimelapseOptionsResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__set_timelapse_options_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__set_timelapse_options__field_descriptors[2] =
{
  {
    "timelapse_options",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__SetTimelapseOptions, timelapse_options),
    &insta360__messages__timelapse_options__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__SetTimelapseOptions, mode),
    &insta360__messages__timelapse_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__set_timelapse_options__field_indices_by_name[] = {
  1,   /* field[1] = mode */
  0,   /* field[0] = timelapse_options */
};
static const ProtobufCIntRange insta360__messages__set_timelapse_options__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__set_timelapse_options__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.SetTimelapseOptions",
  "SetTimelapseOptions",
  "Insta360__Messages__SetTimelapseOptions",
  "insta360.messages",
  sizeof(Insta360__Messages__SetTimelapseOptions),
  2,
  insta360__messages__set_timelapse_options__field_descriptors,
  insta360__messages__set_timelapse_options__field_indices_by_name,
  1,  insta360__messages__set_timelapse_options__number_ranges,
  (ProtobufCMessageInit) insta360__messages__set_timelapse_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define insta360__messages__set_timelapse_options_resp__field_descriptors NULL
#define insta360__messages__set_timelapse_options_resp__field_indices_by_name NULL
#define insta360__messages__set_timelapse_options_resp__number_ranges NULL
const ProtobufCMessageDescriptor insta360__messages__set_timelapse_options_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.SetTimelapseOptionsResp",
  "SetTimelapseOptionsResp",
  "Insta360__Messages__SetTimelapseOptionsResp",
  "insta360.messages",
  sizeof(Insta360__Messages__SetTimelapseOptionsResp),
  0,
  insta360__messages__set_timelapse_options_resp__field_descriptors,
  insta360__messages__set_timelapse_options_resp__field_indices_by_name,
  0,  insta360__messages__set_timelapse_options_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__set_timelapse_options_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
