/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: set_sync_capture_mode.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "set_sync_capture_mode.pb-c.h"
void   insta360__messages__set_sync_capture_mode__init
                     (Insta360__Messages__SetSyncCaptureMode         *message)
{
  static const Insta360__Messages__SetSyncCaptureMode init_value = INSTA360__MESSAGES__SET_SYNC_CAPTURE_MODE__INIT;
  *message = init_value;
}
size_t insta360__messages__set_sync_capture_mode__get_packed_size
                     (const Insta360__Messages__SetSyncCaptureMode *message)
{
  assert(message->base.descriptor == &insta360__messages__set_sync_capture_mode__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__set_sync_capture_mode__pack
                     (const Insta360__Messages__SetSyncCaptureMode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__set_sync_capture_mode__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__set_sync_capture_mode__pack_to_buffer
                     (const Insta360__Messages__SetSyncCaptureMode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__set_sync_capture_mode__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__SetSyncCaptureMode *
       insta360__messages__set_sync_capture_mode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__SetSyncCaptureMode *)
     protobuf_c_message_unpack (&insta360__messages__set_sync_capture_mode__descriptor,
                                allocator, len, data);
}
void   insta360__messages__set_sync_capture_mode__free_unpacked
                     (Insta360__Messages__SetSyncCaptureMode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__set_sync_capture_mode__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__set_sync_capture_mode_resp__init
                     (Insta360__Messages__SetSyncCaptureModeResp         *message)
{
  static const Insta360__Messages__SetSyncCaptureModeResp init_value = INSTA360__MESSAGES__SET_SYNC_CAPTURE_MODE_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__set_sync_capture_mode_resp__get_packed_size
                     (const Insta360__Messages__SetSyncCaptureModeResp *message)
{
  assert(message->base.descriptor == &insta360__messages__set_sync_capture_mode_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__set_sync_capture_mode_resp__pack
                     (const Insta360__Messages__SetSyncCaptureModeResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__set_sync_capture_mode_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__set_sync_capture_mode_resp__pack_to_buffer
                     (const Insta360__Messages__SetSyncCaptureModeResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__set_sync_capture_mode_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__SetSyncCaptureModeResp *
       insta360__messages__set_sync_capture_mode_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__SetSyncCaptureModeResp *)
     protobuf_c_message_unpack (&insta360__messages__set_sync_capture_mode_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__set_sync_capture_mode_resp__free_unpacked
                     (Insta360__Messages__SetSyncCaptureModeResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__set_sync_capture_mode_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__set_sync_capture_mode__field_descriptors[1] =
{
  {
    "capture_mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__SetSyncCaptureMode, capture_mode),
    &insta360__messages__sync_capture_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__set_sync_capture_mode__field_indices_by_name[] = {
  0,   /* field[0] = capture_mode */
};
static const ProtobufCIntRange insta360__messages__set_sync_capture_mode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__set_sync_capture_mode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.SetSyncCaptureMode",
  "SetSyncCaptureMode",
  "Insta360__Messages__SetSyncCaptureMode",
  "insta360.messages",
  sizeof(Insta360__Messages__SetSyncCaptureMode),
  1,
  insta360__messages__set_sync_capture_mode__field_descriptors,
  insta360__messages__set_sync_capture_mode__field_indices_by_name,
  1,  insta360__messages__set_sync_capture_mode__number_ranges,
  (ProtobufCMessageInit) insta360__messages__set_sync_capture_mode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define insta360__messages__set_sync_capture_mode_resp__field_descriptors NULL
#define insta360__messages__set_sync_capture_mode_resp__field_indices_by_name NULL
#define insta360__messages__set_sync_capture_mode_resp__number_ranges NULL
const ProtobufCMessageDescriptor insta360__messages__set_sync_capture_mode_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.SetSyncCaptureModeResp",
  "SetSyncCaptureModeResp",
  "Insta360__Messages__SetSyncCaptureModeResp",
  "insta360.messages",
  sizeof(Insta360__Messages__SetSyncCaptureModeResp),
  0,
  insta360__messages__set_sync_capture_mode_resp__field_descriptors,
  insta360__messages__set_sync_capture_mode_resp__field_indices_by_name,
  0,  insta360__messages__set_sync_capture_mode_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__set_sync_capture_mode_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
