/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: start_timelapse.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "start_timelapse.pb-c.h"
void   insta360__messages__start_timelapse__init
                     (Insta360__Messages__StartTimelapse         *message)
{
  static const Insta360__Messages__StartTimelapse init_value = INSTA360__MESSAGES__START_TIMELAPSE__INIT;
  *message = init_value;
}
size_t insta360__messages__start_timelapse__get_packed_size
                     (const Insta360__Messages__StartTimelapse *message)
{
  assert(message->base.descriptor == &insta360__messages__start_timelapse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__start_timelapse__pack
                     (const Insta360__Messages__StartTimelapse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__start_timelapse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__start_timelapse__pack_to_buffer
                     (const Insta360__Messages__StartTimelapse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__start_timelapse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__StartTimelapse *
       insta360__messages__start_timelapse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__StartTimelapse *)
     protobuf_c_message_unpack (&insta360__messages__start_timelapse__descriptor,
                                allocator, len, data);
}
void   insta360__messages__start_timelapse__free_unpacked
                     (Insta360__Messages__StartTimelapse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__start_timelapse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__start_timelapse_resp__init
                     (Insta360__Messages__StartTimelapseResp         *message)
{
  static const Insta360__Messages__StartTimelapseResp init_value = INSTA360__MESSAGES__START_TIMELAPSE_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__start_timelapse_resp__get_packed_size
                     (const Insta360__Messages__StartTimelapseResp *message)
{
  assert(message->base.descriptor == &insta360__messages__start_timelapse_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__start_timelapse_resp__pack
                     (const Insta360__Messages__StartTimelapseResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__start_timelapse_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__start_timelapse_resp__pack_to_buffer
                     (const Insta360__Messages__StartTimelapseResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__start_timelapse_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__StartTimelapseResp *
       insta360__messages__start_timelapse_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__StartTimelapseResp *)
     protobuf_c_message_unpack (&insta360__messages__start_timelapse_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__start_timelapse_resp__free_unpacked
                     (Insta360__Messages__StartTimelapseResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__start_timelapse_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__start_timelapse__field_descriptors[2] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartTimelapse, mode),
    &insta360__messages__timelapse_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extra_metadata",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartTimelapse, extra_metadata),
    &insta360__messages__extra_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__start_timelapse__field_indices_by_name[] = {
  1,   /* field[1] = extra_metadata */
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange insta360__messages__start_timelapse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor insta360__messages__start_timelapse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.StartTimelapse",
  "StartTimelapse",
  "Insta360__Messages__StartTimelapse",
  "insta360.messages",
  sizeof(Insta360__Messages__StartTimelapse),
  2,
  insta360__messages__start_timelapse__field_descriptors,
  insta360__messages__start_timelapse__field_indices_by_name,
  1,  insta360__messages__start_timelapse__number_ranges,
  (ProtobufCMessageInit) insta360__messages__start_timelapse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define insta360__messages__start_timelapse_resp__field_descriptors NULL
#define insta360__messages__start_timelapse_resp__field_indices_by_name NULL
#define insta360__messages__start_timelapse_resp__number_ranges NULL
const ProtobufCMessageDescriptor insta360__messages__start_timelapse_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.StartTimelapseResp",
  "StartTimelapseResp",
  "Insta360__Messages__StartTimelapseResp",
  "insta360.messages",
  sizeof(Insta360__Messages__StartTimelapseResp),
  0,
  insta360__messages__start_timelapse_resp__field_descriptors,
  insta360__messages__start_timelapse_resp__field_indices_by_name,
  0,  insta360__messages__start_timelapse_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__start_timelapse_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
