/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: start_live_stream.proto */

#ifndef PROTOBUF_C_start_5flive_5fstream_2eproto__INCLUDED
#define PROTOBUF_C_start_5flive_5fstream_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "video.pb-c.h"
#include "media.pb-c.h"

typedef struct Insta360__Messages__StartLiveStream Insta360__Messages__StartLiveStream;
typedef struct Insta360__Messages__StartLiveStreamResp Insta360__Messages__StartLiveStreamResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__StartLiveStream
{
  ProtobufCMessage base;
  protobuf_c_boolean enableaudio;
  protobuf_c_boolean enablevideo;
  Insta360__Messages__AACBSType audiotype;
  uint32_t audiosamplerate;
  uint32_t audiobitrate;
  uint32_t videobitrate;
  Insta360__Messages__VideoResolution resolution;
  protobuf_c_boolean enablegyro;
  uint32_t videobitrate1;
  Insta360__Messages__VideoResolution resolution1;
  uint32_t previewstreamnum;
};
#define INSTA360__MESSAGES__START_LIVE_STREAM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__start_live_stream__descriptor) \
    , 0, 0, INSTA360__MESSAGES__AACBSTYPE__RAW, 0, 0, 0, INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_3840_1920P30, 0, 0, INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_3840_1920P30, 0 }


struct  Insta360__Messages__StartLiveStreamResp
{
  ProtobufCMessage base;
};
#define INSTA360__MESSAGES__START_LIVE_STREAM_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__start_live_stream_resp__descriptor) \
     }


/* Insta360__Messages__StartLiveStream methods */
void   insta360__messages__start_live_stream__init
                     (Insta360__Messages__StartLiveStream         *message);
size_t insta360__messages__start_live_stream__get_packed_size
                     (const Insta360__Messages__StartLiveStream   *message);
size_t insta360__messages__start_live_stream__pack
                     (const Insta360__Messages__StartLiveStream   *message,
                      uint8_t             *out);
size_t insta360__messages__start_live_stream__pack_to_buffer
                     (const Insta360__Messages__StartLiveStream   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__StartLiveStream *
       insta360__messages__start_live_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__start_live_stream__free_unpacked
                     (Insta360__Messages__StartLiveStream *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__StartLiveStreamResp methods */
void   insta360__messages__start_live_stream_resp__init
                     (Insta360__Messages__StartLiveStreamResp         *message);
size_t insta360__messages__start_live_stream_resp__get_packed_size
                     (const Insta360__Messages__StartLiveStreamResp   *message);
size_t insta360__messages__start_live_stream_resp__pack
                     (const Insta360__Messages__StartLiveStreamResp   *message,
                      uint8_t             *out);
size_t insta360__messages__start_live_stream_resp__pack_to_buffer
                     (const Insta360__Messages__StartLiveStreamResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__StartLiveStreamResp *
       insta360__messages__start_live_stream_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__start_live_stream_resp__free_unpacked
                     (Insta360__Messages__StartLiveStreamResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__StartLiveStream_Closure)
                 (const Insta360__Messages__StartLiveStream *message,
                  void *closure_data);
typedef void (*Insta360__Messages__StartLiveStreamResp_Closure)
                 (const Insta360__Messages__StartLiveStreamResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__start_live_stream__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__start_live_stream_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_start_5flive_5fstream_2eproto__INCLUDED */
