/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: start_live_stream.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "start_live_stream.pb-c.h"
void   insta360__messages__start_live_stream__init
                     (Insta360__Messages__StartLiveStream         *message)
{
  static const Insta360__Messages__StartLiveStream init_value = INSTA360__MESSAGES__START_LIVE_STREAM__INIT;
  *message = init_value;
}
size_t insta360__messages__start_live_stream__get_packed_size
                     (const Insta360__Messages__StartLiveStream *message)
{
  assert(message->base.descriptor == &insta360__messages__start_live_stream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__start_live_stream__pack
                     (const Insta360__Messages__StartLiveStream *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__start_live_stream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__start_live_stream__pack_to_buffer
                     (const Insta360__Messages__StartLiveStream *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__start_live_stream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__StartLiveStream *
       insta360__messages__start_live_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__StartLiveStream *)
     protobuf_c_message_unpack (&insta360__messages__start_live_stream__descriptor,
                                allocator, len, data);
}
void   insta360__messages__start_live_stream__free_unpacked
                     (Insta360__Messages__StartLiveStream *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__start_live_stream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__start_live_stream_resp__init
                     (Insta360__Messages__StartLiveStreamResp         *message)
{
  static const Insta360__Messages__StartLiveStreamResp init_value = INSTA360__MESSAGES__START_LIVE_STREAM_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__start_live_stream_resp__get_packed_size
                     (const Insta360__Messages__StartLiveStreamResp *message)
{
  assert(message->base.descriptor == &insta360__messages__start_live_stream_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__start_live_stream_resp__pack
                     (const Insta360__Messages__StartLiveStreamResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__start_live_stream_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__start_live_stream_resp__pack_to_buffer
                     (const Insta360__Messages__StartLiveStreamResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__start_live_stream_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__StartLiveStreamResp *
       insta360__messages__start_live_stream_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__StartLiveStreamResp *)
     protobuf_c_message_unpack (&insta360__messages__start_live_stream_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__start_live_stream_resp__free_unpacked
                     (Insta360__Messages__StartLiveStreamResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__start_live_stream_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__start_live_stream__field_descriptors[11] =
{
  {
    "enableAudio",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, enableaudio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enableVideo",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, enablevideo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audioType",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, audiotype),
    &insta360__messages__aacbstype__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audioSampleRate",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, audiosamplerate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audioBitrate",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, audiobitrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "videoBitrate",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, videobitrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resolution",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, resolution),
    &insta360__messages__video_resolution__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enableGyro",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, enablegyro),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "videoBitrate1",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, videobitrate1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resolution1",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, resolution1),
    &insta360__messages__video_resolution__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previewStreamNum",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StartLiveStream, previewstreamnum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__start_live_stream__field_indices_by_name[] = {
  4,   /* field[4] = audioBitrate */
  3,   /* field[3] = audioSampleRate */
  2,   /* field[2] = audioType */
  0,   /* field[0] = enableAudio */
  7,   /* field[7] = enableGyro */
  1,   /* field[1] = enableVideo */
  10,   /* field[10] = previewStreamNum */
  6,   /* field[6] = resolution */
  9,   /* field[9] = resolution1 */
  5,   /* field[5] = videoBitrate */
  8,   /* field[8] = videoBitrate1 */
};
static const ProtobufCIntRange insta360__messages__start_live_stream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor insta360__messages__start_live_stream__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.StartLiveStream",
  "StartLiveStream",
  "Insta360__Messages__StartLiveStream",
  "insta360.messages",
  sizeof(Insta360__Messages__StartLiveStream),
  11,
  insta360__messages__start_live_stream__field_descriptors,
  insta360__messages__start_live_stream__field_indices_by_name,
  1,  insta360__messages__start_live_stream__number_ranges,
  (ProtobufCMessageInit) insta360__messages__start_live_stream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define insta360__messages__start_live_stream_resp__field_descriptors NULL
#define insta360__messages__start_live_stream_resp__field_indices_by_name NULL
#define insta360__messages__start_live_stream_resp__number_ranges NULL
const ProtobufCMessageDescriptor insta360__messages__start_live_stream_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.StartLiveStreamResp",
  "StartLiveStreamResp",
  "Insta360__Messages__StartLiveStreamResp",
  "insta360.messages",
  sizeof(Insta360__Messages__StartLiveStreamResp),
  0,
  insta360__messages__start_live_stream_resp__field_descriptors,
  insta360__messages__start_live_stream_resp__field_indices_by_name,
  0,  insta360__messages__start_live_stream_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__start_live_stream_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
