/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stop_bullettime.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "stop_bullettime.pb-c.h"
void   insta360__messages__stop_bullet_time__init
                     (Insta360__Messages__StopBulletTime         *message)
{
  static const Insta360__Messages__StopBulletTime init_value = INSTA360__MESSAGES__STOP_BULLET_TIME__INIT;
  *message = init_value;
}
size_t insta360__messages__stop_bullet_time__get_packed_size
                     (const Insta360__Messages__StopBulletTime *message)
{
  assert(message->base.descriptor == &insta360__messages__stop_bullet_time__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__stop_bullet_time__pack
                     (const Insta360__Messages__StopBulletTime *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__stop_bullet_time__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__stop_bullet_time__pack_to_buffer
                     (const Insta360__Messages__StopBulletTime *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__stop_bullet_time__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__StopBulletTime *
       insta360__messages__stop_bullet_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__StopBulletTime *)
     protobuf_c_message_unpack (&insta360__messages__stop_bullet_time__descriptor,
                                allocator, len, data);
}
void   insta360__messages__stop_bullet_time__free_unpacked
                     (Insta360__Messages__StopBulletTime *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__stop_bullet_time__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__stop_bullet_time_resp__init
                     (Insta360__Messages__StopBulletTimeResp         *message)
{
  static const Insta360__Messages__StopBulletTimeResp init_value = INSTA360__MESSAGES__STOP_BULLET_TIME_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__stop_bullet_time_resp__get_packed_size
                     (const Insta360__Messages__StopBulletTimeResp *message)
{
  assert(message->base.descriptor == &insta360__messages__stop_bullet_time_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__stop_bullet_time_resp__pack
                     (const Insta360__Messages__StopBulletTimeResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__stop_bullet_time_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__stop_bullet_time_resp__pack_to_buffer
                     (const Insta360__Messages__StopBulletTimeResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__stop_bullet_time_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__StopBulletTimeResp *
       insta360__messages__stop_bullet_time_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__StopBulletTimeResp *)
     protobuf_c_message_unpack (&insta360__messages__stop_bullet_time_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__stop_bullet_time_resp__free_unpacked
                     (Insta360__Messages__StopBulletTimeResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__stop_bullet_time_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__stop_bullet_time__field_descriptors[1] =
{
  {
    "extra_metadata",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StopBulletTime, extra_metadata),
    &insta360__messages__extra_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__stop_bullet_time__field_indices_by_name[] = {
  0,   /* field[0] = extra_metadata */
};
static const ProtobufCIntRange insta360__messages__stop_bullet_time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__stop_bullet_time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.StopBulletTime",
  "StopBulletTime",
  "Insta360__Messages__StopBulletTime",
  "insta360.messages",
  sizeof(Insta360__Messages__StopBulletTime),
  1,
  insta360__messages__stop_bullet_time__field_descriptors,
  insta360__messages__stop_bullet_time__field_indices_by_name,
  1,  insta360__messages__stop_bullet_time__number_ranges,
  (ProtobufCMessageInit) insta360__messages__stop_bullet_time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__stop_bullet_time_resp__field_descriptors[1] =
{
  {
    "video",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StopBulletTimeResp, video),
    &insta360__messages__video__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__stop_bullet_time_resp__field_indices_by_name[] = {
  0,   /* field[0] = video */
};
static const ProtobufCIntRange insta360__messages__stop_bullet_time_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__stop_bullet_time_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.StopBulletTimeResp",
  "StopBulletTimeResp",
  "Insta360__Messages__StopBulletTimeResp",
  "insta360.messages",
  sizeof(Insta360__Messages__StopBulletTimeResp),
  1,
  insta360__messages__stop_bullet_time_resp__field_descriptors,
  insta360__messages__stop_bullet_time_resp__field_indices_by_name,
  1,  insta360__messages__stop_bullet_time_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__stop_bullet_time_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
