/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stop_bullettime.proto */

#ifndef PROTOBUF_C_stop_5fbullettime_2eproto__INCLUDED
#define PROTOBUF_C_stop_5fbullettime_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "video.pb-c.h"
#include "extra_info.pb-c.h"

typedef struct Insta360__Messages__StopBulletTime Insta360__Messages__StopBulletTime;
typedef struct Insta360__Messages__StopBulletTimeResp Insta360__Messages__StopBulletTimeResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__StopBulletTime
{
  ProtobufCMessage base;
  Insta360__Messages__ExtraMetadata *extra_metadata;
};
#define INSTA360__MESSAGES__STOP_BULLET_TIME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__stop_bullet_time__descriptor) \
    , NULL }


struct  Insta360__Messages__StopBulletTimeResp
{
  ProtobufCMessage base;
  Insta360__Messages__Video *video;
};
#define INSTA360__MESSAGES__STOP_BULLET_TIME_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__stop_bullet_time_resp__descriptor) \
    , NULL }


/* Insta360__Messages__StopBulletTime methods */
void   insta360__messages__stop_bullet_time__init
                     (Insta360__Messages__StopBulletTime         *message);
size_t insta360__messages__stop_bullet_time__get_packed_size
                     (const Insta360__Messages__StopBulletTime   *message);
size_t insta360__messages__stop_bullet_time__pack
                     (const Insta360__Messages__StopBulletTime   *message,
                      uint8_t             *out);
size_t insta360__messages__stop_bullet_time__pack_to_buffer
                     (const Insta360__Messages__StopBulletTime   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__StopBulletTime *
       insta360__messages__stop_bullet_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__stop_bullet_time__free_unpacked
                     (Insta360__Messages__StopBulletTime *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__StopBulletTimeResp methods */
void   insta360__messages__stop_bullet_time_resp__init
                     (Insta360__Messages__StopBulletTimeResp         *message);
size_t insta360__messages__stop_bullet_time_resp__get_packed_size
                     (const Insta360__Messages__StopBulletTimeResp   *message);
size_t insta360__messages__stop_bullet_time_resp__pack
                     (const Insta360__Messages__StopBulletTimeResp   *message,
                      uint8_t             *out);
size_t insta360__messages__stop_bullet_time_resp__pack_to_buffer
                     (const Insta360__Messages__StopBulletTimeResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__StopBulletTimeResp *
       insta360__messages__stop_bullet_time_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__stop_bullet_time_resp__free_unpacked
                     (Insta360__Messages__StopBulletTimeResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__StopBulletTime_Closure)
                 (const Insta360__Messages__StopBulletTime *message,
                  void *closure_data);
typedef void (*Insta360__Messages__StopBulletTimeResp_Closure)
                 (const Insta360__Messages__StopBulletTimeResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__stop_bullet_time__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__stop_bullet_time_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_stop_5fbullettime_2eproto__INCLUDED */
