/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: storage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "storage.pb-c.h"
void   insta360__messages__storage_state__init
                     (Insta360__Messages__StorageState         *message)
{
  static const Insta360__Messages__StorageState init_value = INSTA360__MESSAGES__STORAGE_STATE__INIT;
  *message = init_value;
}
size_t insta360__messages__storage_state__get_packed_size
                     (const Insta360__Messages__StorageState *message)
{
  assert(message->base.descriptor == &insta360__messages__storage_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__storage_state__pack
                     (const Insta360__Messages__StorageState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__storage_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__storage_state__pack_to_buffer
                     (const Insta360__Messages__StorageState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__storage_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__StorageState *
       insta360__messages__storage_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__StorageState *)
     protobuf_c_message_unpack (&insta360__messages__storage_state__descriptor,
                                allocator, len, data);
}
void   insta360__messages__storage_state__free_unpacked
                     (Insta360__Messages__StorageState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__storage_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__storage_state__field_descriptors[3] =
{
  {
    "card_state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StorageState, card_state),
    &insta360__messages__card_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "free_space",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StorageState, free_space),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_space",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__StorageState, total_space),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__storage_state__field_indices_by_name[] = {
  0,   /* field[0] = card_state */
  1,   /* field[1] = free_space */
  2,   /* field[2] = total_space */
};
static const ProtobufCIntRange insta360__messages__storage_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor insta360__messages__storage_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.StorageState",
  "StorageState",
  "Insta360__Messages__StorageState",
  "insta360.messages",
  sizeof(Insta360__Messages__StorageState),
  3,
  insta360__messages__storage_state__field_descriptors,
  insta360__messages__storage_state__field_indices_by_name,
  1,  insta360__messages__storage_state__number_ranges,
  (ProtobufCMessageInit) insta360__messages__storage_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue insta360__messages__card_state__enum_values_by_number[6] =
{
  { "STOR_CS_PASS", "INSTA360__MESSAGES__CARD_STATE__STOR_CS_PASS", 0 },
  { "STOR_CS_NOCARD", "INSTA360__MESSAGES__CARD_STATE__STOR_CS_NOCARD", 1 },
  { "STOR_CS_NOSPACE", "INSTA360__MESSAGES__CARD_STATE__STOR_CS_NOSPACE", 2 },
  { "STOR_CS_INVALID_FORMAT", "INSTA360__MESSAGES__CARD_STATE__STOR_CS_INVALID_FORMAT", 3 },
  { "STOR_CS_WPCARD", "INSTA360__MESSAGES__CARD_STATE__STOR_CS_WPCARD", 4 },
  { "STOR_CS_OTHER_ERROR", "INSTA360__MESSAGES__CARD_STATE__STOR_CS_OTHER_ERROR", 5 },
};
static const ProtobufCIntRange insta360__messages__card_state__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex insta360__messages__card_state__enum_values_by_name[6] =
{
  { "STOR_CS_INVALID_FORMAT", 3 },
  { "STOR_CS_NOCARD", 1 },
  { "STOR_CS_NOSPACE", 2 },
  { "STOR_CS_OTHER_ERROR", 5 },
  { "STOR_CS_PASS", 0 },
  { "STOR_CS_WPCARD", 4 },
};
const ProtobufCEnumDescriptor insta360__messages__card_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.CardState",
  "CardState",
  "Insta360__Messages__CardState",
  "insta360.messages",
  6,
  insta360__messages__card_state__enum_values_by_number,
  6,
  insta360__messages__card_state__enum_values_by_name,
  1,
  insta360__messages__card_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
