/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sync_capture_mode.proto */

#ifndef PROTOBUF_C_sync_5fcapture_5fmode_2eproto__INCLUDED
#define PROTOBUF_C_sync_5fcapture_5fmode_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Insta360__Messages__SyncCaptureMode {
  INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_UNKNOWN = 0,
  INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_NORMAL_IMAGE = 1,
  INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_NORMAL_VIDEO = 2,
  INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_HDR_IMAGE = 3,
  INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_HDR_VIDEO = 4,
  INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_INTERVAL_IMAGE = 5,
  INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_TIMELAPSE_VIDEO = 6,
  INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_BURST_PHOTO = 7,
  INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_BULLETTIME_VIDEO = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__SYNC_CAPTURE_MODE)
} Insta360__Messages__SyncCaptureMode;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    insta360__messages__sync_capture_mode__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sync_5fcapture_5fmode_2eproto__INCLUDED */
