/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sync_capture_mode.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sync_capture_mode.pb-c.h"
static const ProtobufCEnumValue insta360__messages__sync_capture_mode__enum_values_by_number[9] =
{
  { "SYNC_MODE_UNKNOWN", "INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_UNKNOWN", 0 },
  { "SYNC_MODE_NORMAL_IMAGE", "INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_NORMAL_IMAGE", 1 },
  { "SYNC_MODE_NORMAL_VIDEO", "INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_NORMAL_VIDEO", 2 },
  { "SYNC_MODE_HDR_IMAGE", "INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_HDR_IMAGE", 3 },
  { "SYNC_MODE_HDR_VIDEO", "INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_HDR_VIDEO", 4 },
  { "SYNC_MODE_INTERVAL_IMAGE", "INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_INTERVAL_IMAGE", 5 },
  { "SYNC_MODE_TIMELAPSE_VIDEO", "INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_TIMELAPSE_VIDEO", 6 },
  { "SYNC_MODE_BURST_PHOTO", "INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_BURST_PHOTO", 7 },
  { "SYNC_MODE_BULLETTIME_VIDEO", "INSTA360__MESSAGES__SYNC_CAPTURE_MODE__SYNC_MODE_BULLETTIME_VIDEO", 8 },
};
static const ProtobufCIntRange insta360__messages__sync_capture_mode__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex insta360__messages__sync_capture_mode__enum_values_by_name[9] =
{
  { "SYNC_MODE_BULLETTIME_VIDEO", 8 },
  { "SYNC_MODE_BURST_PHOTO", 7 },
  { "SYNC_MODE_HDR_IMAGE", 3 },
  { "SYNC_MODE_HDR_VIDEO", 4 },
  { "SYNC_MODE_INTERVAL_IMAGE", 5 },
  { "SYNC_MODE_NORMAL_IMAGE", 1 },
  { "SYNC_MODE_NORMAL_VIDEO", 2 },
  { "SYNC_MODE_TIMELAPSE_VIDEO", 6 },
  { "SYNC_MODE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor insta360__messages__sync_capture_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.SyncCaptureMode",
  "SyncCaptureMode",
  "Insta360__Messages__SyncCaptureMode",
  "insta360.messages",
  9,
  insta360__messages__sync_capture_mode__enum_values_by_number,
  9,
  insta360__messages__sync_capture_mode__enum_values_by_name,
  1,
  insta360__messages__sync_capture_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
