/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: take_picture.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "take_picture.pb-c.h"
void   insta360__messages__take_picture__init
                     (Insta360__Messages__TakePicture         *message)
{
  static const Insta360__Messages__TakePicture init_value = INSTA360__MESSAGES__TAKE_PICTURE__INIT;
  *message = init_value;
}
size_t insta360__messages__take_picture__get_packed_size
                     (const Insta360__Messages__TakePicture *message)
{
  assert(message->base.descriptor == &insta360__messages__take_picture__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__take_picture__pack
                     (const Insta360__Messages__TakePicture *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__take_picture__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__take_picture__pack_to_buffer
                     (const Insta360__Messages__TakePicture *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__take_picture__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__TakePicture *
       insta360__messages__take_picture__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__TakePicture *)
     protobuf_c_message_unpack (&insta360__messages__take_picture__descriptor,
                                allocator, len, data);
}
void   insta360__messages__take_picture__free_unpacked
                     (Insta360__Messages__TakePicture *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__take_picture__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__take_picture_response__init
                     (Insta360__Messages__TakePictureResponse         *message)
{
  static const Insta360__Messages__TakePictureResponse init_value = INSTA360__MESSAGES__TAKE_PICTURE_RESPONSE__INIT;
  *message = init_value;
}
size_t insta360__messages__take_picture_response__get_packed_size
                     (const Insta360__Messages__TakePictureResponse *message)
{
  assert(message->base.descriptor == &insta360__messages__take_picture_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__take_picture_response__pack
                     (const Insta360__Messages__TakePictureResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__take_picture_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__take_picture_response__pack_to_buffer
                     (const Insta360__Messages__TakePictureResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__take_picture_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__TakePictureResponse *
       insta360__messages__take_picture_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__TakePictureResponse *)
     protobuf_c_message_unpack (&insta360__messages__take_picture_response__descriptor,
                                allocator, len, data);
}
void   insta360__messages__take_picture_response__free_unpacked
                     (Insta360__Messages__TakePictureResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__take_picture_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue insta360__messages__take_picture__mode__enum_values_by_number[4] =
{
  { "NORMAL", "INSTA360__MESSAGES__TAKE_PICTURE__MODE__NORMAL", 0 },
  { "AEB", "INSTA360__MESSAGES__TAKE_PICTURE__MODE__AEB", 1 },
  { "RAW", "INSTA360__MESSAGES__TAKE_PICTURE__MODE__RAW", 2 },
  { "BURST", "INSTA360__MESSAGES__TAKE_PICTURE__MODE__BURST", 3 },
};
static const ProtobufCIntRange insta360__messages__take_picture__mode__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex insta360__messages__take_picture__mode__enum_values_by_name[4] =
{
  { "AEB", 1 },
  { "BURST", 3 },
  { "NORMAL", 0 },
  { "RAW", 2 },
};
const ProtobufCEnumDescriptor insta360__messages__take_picture__mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.TakePicture.Mode",
  "Mode",
  "Insta360__Messages__TakePicture__Mode",
  "insta360.messages",
  4,
  insta360__messages__take_picture__mode__enum_values_by_number,
  4,
  insta360__messages__take_picture__mode__enum_values_by_name,
  1,
  insta360__messages__take_picture__mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor insta360__messages__take_picture__field_descriptors[3] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__TakePicture, mode),
    &insta360__messages__take_picture__mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extra_metadata",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__TakePicture, extra_metadata),
    &insta360__messages__extra_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aeb_ev_bias",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Insta360__Messages__TakePicture, n_aeb_ev_bias),
    offsetof(Insta360__Messages__TakePicture, aeb_ev_bias),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__take_picture__field_indices_by_name[] = {
  2,   /* field[2] = aeb_ev_bias */
  1,   /* field[1] = extra_metadata */
  0,   /* field[0] = mode */
};
static const ProtobufCIntRange insta360__messages__take_picture__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor insta360__messages__take_picture__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.TakePicture",
  "TakePicture",
  "Insta360__Messages__TakePicture",
  "insta360.messages",
  sizeof(Insta360__Messages__TakePicture),
  3,
  insta360__messages__take_picture__field_descriptors,
  insta360__messages__take_picture__field_indices_by_name,
  1,  insta360__messages__take_picture__number_ranges,
  (ProtobufCMessageInit) insta360__messages__take_picture__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor insta360__messages__take_picture_response__field_descriptors[3] =
{
  {
    "image",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__TakePictureResponse, image),
    &insta360__messages__photo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aeb_images",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Insta360__Messages__TakePictureResponse, n_aeb_images),
    offsetof(Insta360__Messages__TakePictureResponse, aeb_images),
    &insta360__messages__photo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "burst_images",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Insta360__Messages__TakePictureResponse, n_burst_images),
    offsetof(Insta360__Messages__TakePictureResponse, burst_images),
    &insta360__messages__photo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__take_picture_response__field_indices_by_name[] = {
  1,   /* field[1] = aeb_images */
  2,   /* field[2] = burst_images */
  0,   /* field[0] = image */
};
static const ProtobufCIntRange insta360__messages__take_picture_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor insta360__messages__take_picture_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.TakePictureResponse",
  "TakePictureResponse",
  "Insta360__Messages__TakePictureResponse",
  "insta360.messages",
  sizeof(Insta360__Messages__TakePictureResponse),
  3,
  insta360__messages__take_picture_response__field_descriptors,
  insta360__messages__take_picture_response__field_indices_by_name,
  1,  insta360__messages__take_picture_response__number_ranges,
  (ProtobufCMessageInit) insta360__messages__take_picture_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
