/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: timelapse.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "timelapse.pb-c.h"
void   insta360__messages__timelapse_options__init
                     (Insta360__Messages__TimelapseOptions         *message)
{
  static const Insta360__Messages__TimelapseOptions init_value = INSTA360__MESSAGES__TIMELAPSE_OPTIONS__INIT;
  *message = init_value;
}
size_t insta360__messages__timelapse_options__get_packed_size
                     (const Insta360__Messages__TimelapseOptions *message)
{
  assert(message->base.descriptor == &insta360__messages__timelapse_options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__timelapse_options__pack
                     (const Insta360__Messages__TimelapseOptions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__timelapse_options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__timelapse_options__pack_to_buffer
                     (const Insta360__Messages__TimelapseOptions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__timelapse_options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__TimelapseOptions *
       insta360__messages__timelapse_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__TimelapseOptions *)
     protobuf_c_message_unpack (&insta360__messages__timelapse_options__descriptor,
                                allocator, len, data);
}
void   insta360__messages__timelapse_options__free_unpacked
                     (Insta360__Messages__TimelapseOptions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__timelapse_options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue insta360__messages__timelapse_options__output_type__enum_values_by_number[3] =
{
  { "DoNotChange", "INSTA360__MESSAGES__TIMELAPSE_OPTIONS__OUTPUT_TYPE__DoNotChange", 0 },
  { "Video", "INSTA360__MESSAGES__TIMELAPSE_OPTIONS__OUTPUT_TYPE__Video", 1 },
  { "Images", "INSTA360__MESSAGES__TIMELAPSE_OPTIONS__OUTPUT_TYPE__Images", 2 },
};
static const ProtobufCIntRange insta360__messages__timelapse_options__output_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex insta360__messages__timelapse_options__output_type__enum_values_by_name[3] =
{
  { "DoNotChange", 0 },
  { "Images", 2 },
  { "Video", 1 },
};
const ProtobufCEnumDescriptor insta360__messages__timelapse_options__output_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.TimelapseOptions.OutputType",
  "OutputType",
  "Insta360__Messages__TimelapseOptions__OutputType",
  "insta360.messages",
  3,
  insta360__messages__timelapse_options__output_type__enum_values_by_number,
  3,
  insta360__messages__timelapse_options__output_type__enum_values_by_name,
  1,
  insta360__messages__timelapse_options__output_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor insta360__messages__timelapse_options__field_descriptors[3] =
{
  {
    "duration",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__TimelapseOptions, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lapseTime",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__TimelapseOptions, lapsetime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__TimelapseOptions, output_type),
    &insta360__messages__timelapse_options__output_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__timelapse_options__field_indices_by_name[] = {
  0,   /* field[0] = duration */
  1,   /* field[1] = lapseTime */
  2,   /* field[2] = output_type */
};
static const ProtobufCIntRange insta360__messages__timelapse_options__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor insta360__messages__timelapse_options__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.TimelapseOptions",
  "TimelapseOptions",
  "Insta360__Messages__TimelapseOptions",
  "insta360.messages",
  sizeof(Insta360__Messages__TimelapseOptions),
  3,
  insta360__messages__timelapse_options__field_descriptors,
  insta360__messages__timelapse_options__field_indices_by_name,
  1,  insta360__messages__timelapse_options__number_ranges,
  (ProtobufCMessageInit) insta360__messages__timelapse_options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue insta360__messages__timelapse_mode__enum_values_by_number[3] =
{
  { "TIMELAPSE_MIXED", "INSTA360__MESSAGES__TIMELAPSE_MODE__TIMELAPSE_MIXED", 0 },
  { "TIMELAPSE_VIDEO", "INSTA360__MESSAGES__TIMELAPSE_MODE__TIMELAPSE_VIDEO", 1 },
  { "TIMELAPSE_INTERVAL_SHOOTING", "INSTA360__MESSAGES__TIMELAPSE_MODE__TIMELAPSE_INTERVAL_SHOOTING", 2 },
};
static const ProtobufCIntRange insta360__messages__timelapse_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex insta360__messages__timelapse_mode__enum_values_by_name[3] =
{
  { "TIMELAPSE_INTERVAL_SHOOTING", 2 },
  { "TIMELAPSE_MIXED", 0 },
  { "TIMELAPSE_VIDEO", 1 },
};
const ProtobufCEnumDescriptor insta360__messages__timelapse_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "insta360.messages.TimelapseMode",
  "TimelapseMode",
  "Insta360__Messages__TimelapseMode",
  "insta360.messages",
  3,
  insta360__messages__timelapse_mode__enum_values_by_number,
  3,
  insta360__messages__timelapse_mode__enum_values_by_name,
  1,
  insta360__messages__timelapse_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
