/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: timelapse_status_update.proto */

#ifndef PROTOBUF_C_timelapse_5fstatus_5fupdate_2eproto__INCLUDED
#define PROTOBUF_C_timelapse_5fstatus_5fupdate_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__NotificationTimeLapseStatusUpdate Insta360__Messages__NotificationTimeLapseStatusUpdate;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__NotificationTimeLapseStatusUpdate
{
  ProtobufCMessage base;
  uint32_t interval_count;
};
#define INSTA360__MESSAGES__NOTIFICATION_TIME_LAPSE_STATUS_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__notification_time_lapse_status_update__descriptor) \
    , 0 }


/* Insta360__Messages__NotificationTimeLapseStatusUpdate methods */
void   insta360__messages__notification_time_lapse_status_update__init
                     (Insta360__Messages__NotificationTimeLapseStatusUpdate         *message);
size_t insta360__messages__notification_time_lapse_status_update__get_packed_size
                     (const Insta360__Messages__NotificationTimeLapseStatusUpdate   *message);
size_t insta360__messages__notification_time_lapse_status_update__pack
                     (const Insta360__Messages__NotificationTimeLapseStatusUpdate   *message,
                      uint8_t             *out);
size_t insta360__messages__notification_time_lapse_status_update__pack_to_buffer
                     (const Insta360__Messages__NotificationTimeLapseStatusUpdate   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__NotificationTimeLapseStatusUpdate *
       insta360__messages__notification_time_lapse_status_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__notification_time_lapse_status_update__free_unpacked
                     (Insta360__Messages__NotificationTimeLapseStatusUpdate *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__NotificationTimeLapseStatusUpdate_Closure)
                 (const Insta360__Messages__NotificationTimeLapseStatusUpdate *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__notification_time_lapse_status_update__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_timelapse_5fstatus_5fupdate_2eproto__INCLUDED */
