/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: upload_gps.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "upload_gps.pb-c.h"
void   insta360__messages__upload_gps__init
                     (Insta360__Messages__UploadGps         *message)
{
  static const Insta360__Messages__UploadGps init_value = INSTA360__MESSAGES__UPLOAD_GPS__INIT;
  *message = init_value;
}
size_t insta360__messages__upload_gps__get_packed_size
                     (const Insta360__Messages__UploadGps *message)
{
  assert(message->base.descriptor == &insta360__messages__upload_gps__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__upload_gps__pack
                     (const Insta360__Messages__UploadGps *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__upload_gps__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__upload_gps__pack_to_buffer
                     (const Insta360__Messages__UploadGps *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__upload_gps__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__UploadGps *
       insta360__messages__upload_gps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__UploadGps *)
     protobuf_c_message_unpack (&insta360__messages__upload_gps__descriptor,
                                allocator, len, data);
}
void   insta360__messages__upload_gps__free_unpacked
                     (Insta360__Messages__UploadGps *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__upload_gps__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   insta360__messages__upload_gps_resp__init
                     (Insta360__Messages__UploadGpsResp         *message)
{
  static const Insta360__Messages__UploadGpsResp init_value = INSTA360__MESSAGES__UPLOAD_GPS_RESP__INIT;
  *message = init_value;
}
size_t insta360__messages__upload_gps_resp__get_packed_size
                     (const Insta360__Messages__UploadGpsResp *message)
{
  assert(message->base.descriptor == &insta360__messages__upload_gps_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insta360__messages__upload_gps_resp__pack
                     (const Insta360__Messages__UploadGpsResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insta360__messages__upload_gps_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insta360__messages__upload_gps_resp__pack_to_buffer
                     (const Insta360__Messages__UploadGpsResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insta360__messages__upload_gps_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Insta360__Messages__UploadGpsResp *
       insta360__messages__upload_gps_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Insta360__Messages__UploadGpsResp *)
     protobuf_c_message_unpack (&insta360__messages__upload_gps_resp__descriptor,
                                allocator, len, data);
}
void   insta360__messages__upload_gps_resp__free_unpacked
                     (Insta360__Messages__UploadGpsResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &insta360__messages__upload_gps_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insta360__messages__upload_gps__field_descriptors[1] =
{
  {
    "gps",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Insta360__Messages__UploadGps, gps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insta360__messages__upload_gps__field_indices_by_name[] = {
  0,   /* field[0] = gps */
};
static const ProtobufCIntRange insta360__messages__upload_gps__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insta360__messages__upload_gps__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.UploadGps",
  "UploadGps",
  "Insta360__Messages__UploadGps",
  "insta360.messages",
  sizeof(Insta360__Messages__UploadGps),
  1,
  insta360__messages__upload_gps__field_descriptors,
  insta360__messages__upload_gps__field_indices_by_name,
  1,  insta360__messages__upload_gps__number_ranges,
  (ProtobufCMessageInit) insta360__messages__upload_gps__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define insta360__messages__upload_gps_resp__field_descriptors NULL
#define insta360__messages__upload_gps_resp__field_indices_by_name NULL
#define insta360__messages__upload_gps_resp__number_ranges NULL
const ProtobufCMessageDescriptor insta360__messages__upload_gps_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "insta360.messages.UploadGpsResp",
  "UploadGpsResp",
  "Insta360__Messages__UploadGpsResp",
  "insta360.messages",
  sizeof(Insta360__Messages__UploadGpsResp),
  0,
  insta360__messages__upload_gps_resp__field_descriptors,
  insta360__messages__upload_gps_resp__field_indices_by_name,
  0,  insta360__messages__upload_gps_resp__number_ranges,
  (ProtobufCMessageInit) insta360__messages__upload_gps_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
