/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: upload_gps.proto */

#ifndef PROTOBUF_C_upload_5fgps_2eproto__INCLUDED
#define PROTOBUF_C_upload_5fgps_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__UploadGps Insta360__Messages__UploadGps;
typedef struct Insta360__Messages__UploadGpsResp Insta360__Messages__UploadGpsResp;


/* --- enums --- */


/* --- messages --- */

struct  Insta360__Messages__UploadGps
{
  ProtobufCMessage base;
  ProtobufCBinaryData gps;
};
#define INSTA360__MESSAGES__UPLOAD_GPS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__upload_gps__descriptor) \
    , {0,NULL} }


struct  Insta360__Messages__UploadGpsResp
{
  ProtobufCMessage base;
};
#define INSTA360__MESSAGES__UPLOAD_GPS_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__upload_gps_resp__descriptor) \
     }


/* Insta360__Messages__UploadGps methods */
void   insta360__messages__upload_gps__init
                     (Insta360__Messages__UploadGps         *message);
size_t insta360__messages__upload_gps__get_packed_size
                     (const Insta360__Messages__UploadGps   *message);
size_t insta360__messages__upload_gps__pack
                     (const Insta360__Messages__UploadGps   *message,
                      uint8_t             *out);
size_t insta360__messages__upload_gps__pack_to_buffer
                     (const Insta360__Messages__UploadGps   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__UploadGps *
       insta360__messages__upload_gps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__upload_gps__free_unpacked
                     (Insta360__Messages__UploadGps *message,
                      ProtobufCAllocator *allocator);
/* Insta360__Messages__UploadGpsResp methods */
void   insta360__messages__upload_gps_resp__init
                     (Insta360__Messages__UploadGpsResp         *message);
size_t insta360__messages__upload_gps_resp__get_packed_size
                     (const Insta360__Messages__UploadGpsResp   *message);
size_t insta360__messages__upload_gps_resp__pack
                     (const Insta360__Messages__UploadGpsResp   *message,
                      uint8_t             *out);
size_t insta360__messages__upload_gps_resp__pack_to_buffer
                     (const Insta360__Messages__UploadGpsResp   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__UploadGpsResp *
       insta360__messages__upload_gps_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__upload_gps_resp__free_unpacked
                     (Insta360__Messages__UploadGpsResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__UploadGps_Closure)
                 (const Insta360__Messages__UploadGps *message,
                  void *closure_data);
typedef void (*Insta360__Messages__UploadGpsResp_Closure)
                 (const Insta360__Messages__UploadGpsResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insta360__messages__upload_gps__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__upload_gps_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_upload_5fgps_2eproto__INCLUDED */
