/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: video.proto */

#ifndef PROTOBUF_C_video_2eproto__INCLUDED
#define PROTOBUF_C_video_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Insta360__Messages__Video Insta360__Messages__Video;


/* --- enums --- */

typedef enum _Insta360__Messages__VideoResolution {
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_3840_1920P30 = 0,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_2560_1280P30 = 1,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_1920_960P30 = 2,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_2560_1280P60 = 3,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_2048_512P120 = 4,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_3328_832P60 = 5,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_3072_1536P30 = 6,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_2240_1120P30 = 7,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_2240_1120P24 = 8,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_1440_720P30 = 9,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_2880_2880P30 = 10,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_3840_1920P60 = 11,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_3840_1920P50 = 12,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_3008_1504P100 = 13,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_960_480P30 = 14,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_3040_1520P30 = 15,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_2176_1088P30 = 16,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_720_360P30 = 17,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_480_240P30 = 18,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_2880_2880P25 = 19,
  INSTA360__MESSAGES__VIDEO_RESOLUTION__RES_2880_2880P24 = 20
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__VIDEO_RESOLUTION)
} Insta360__Messages__VideoResolution;
typedef enum _Insta360__Messages__VideoSubMode {
  INSTA360__MESSAGES__VIDEO_SUB_MODE__VIDEO_NORMAL = 0,
  INSTA360__MESSAGES__VIDEO_SUB_MODE__VIDEO_BULLETTIME = 1,
  INSTA360__MESSAGES__VIDEO_SUB_MODE__VIDEO_TIMELAPSE = 2,
  INSTA360__MESSAGES__VIDEO_SUB_MODE__VIDEO_HDR = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(INSTA360__MESSAGES__VIDEO_SUB_MODE)
} Insta360__Messages__VideoSubMode;

/* --- messages --- */

struct  Insta360__Messages__Video
{
  ProtobufCMessage base;
  char *uri;
  uint64_t file_size;
  uint32_t total_time;
};
#define INSTA360__MESSAGES__VIDEO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insta360__messages__video__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0 }


/* Insta360__Messages__Video methods */
void   insta360__messages__video__init
                     (Insta360__Messages__Video         *message);
size_t insta360__messages__video__get_packed_size
                     (const Insta360__Messages__Video   *message);
size_t insta360__messages__video__pack
                     (const Insta360__Messages__Video   *message,
                      uint8_t             *out);
size_t insta360__messages__video__pack_to_buffer
                     (const Insta360__Messages__Video   *message,
                      ProtobufCBuffer     *buffer);
Insta360__Messages__Video *
       insta360__messages__video__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insta360__messages__video__free_unpacked
                     (Insta360__Messages__Video *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Insta360__Messages__Video_Closure)
                 (const Insta360__Messages__Video *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    insta360__messages__video_resolution__descriptor;
extern const ProtobufCEnumDescriptor    insta360__messages__video_sub_mode__descriptor;
extern const ProtobufCMessageDescriptor insta360__messages__video__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_video_2eproto__INCLUDED */
